// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn5AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn15AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn18AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn19AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn32AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn29AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn34AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn37AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn39AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn46AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn48AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn50AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn54AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn56AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agent/compact"

				if l := len("agent/compact"); len(elem) >= l && elem[0:l] == "agent/compact" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleAgentCompactRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'b': // Prefix: "boredom"

				if l := len("boredom"); len(elem) >= l && elem[0:l] == "boredom" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleBoredomGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'h': // Prefix: "hannel"

					if l := len("hannel"); len(elem) >= l && elem[0:l] == "hannel" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '-': // Prefix: "-settings"

						if l := len("-settings"); len(elem) >= l && elem[0:l] == "-settings" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleChannelSettingsListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "channelId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleChannelSettingsDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleChannelSettingsUpdateRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,PUT",
										allowedHeaders: rn5AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleChannelsListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'o': // Prefix: "on"

					if l := len("on"); len(elem) >= l && elem[0:l] == "on" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 't': // Prefix: "text"

						if l := len("text"); len(elem) >= l && elem[0:l] == "text" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleContextGetRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'v': // Prefix: "versation-logs"

						if l := len("versation-logs"); len(elem) >= l && elem[0:l] == "versation-logs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleConversationLogsListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/export"

							if l := len("/export"); len(elem) >= l && elem[0:l] == "/export" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleConversationLogsExportRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'd': // Prefix: "diary"

				if l := len("diary"); len(elem) >= l && elem[0:l] == "diary" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleDiaryListRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'f': // Prefix: "forget/"

				if l := len("forget/"); len(elem) >= l && elem[0:l] == "forget/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "delete"

					if l := len("delete"); len(elem) >= l && elem[0:l] == "delete" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleForgetDeleteRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn15AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'g': // Prefix: "groups"

					if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleForgetGroupsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'm': // Prefix: "merge"

					if l := len("merge"); len(elem) >= l && elem[0:l] == "merge" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleForgetMergeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn18AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'r': // Prefix: "run"

					if l := len("run"); len(elem) >= l && elem[0:l] == "run" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleForgetRunRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn19AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "status"

					if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleForgetStatusRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'g': // Prefix: "guilds"

				if l := len("guilds"); len(elem) >= l && elem[0:l] == "guilds" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGuildsListRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/channels"

						if l := len("/channels"); len(elem) >= l && elem[0:l] == "/channels" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGuildsChannelsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleHealthCheckRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'i': // Prefix: "identity"

				if l := len("identity"); len(elem) >= l && elem[0:l] == "identity" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleIdentityGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'l': // Prefix: "l"

				if l := len("l"); len(elem) >= l && elem[0:l] == "l" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "lm"

					if l := len("lm"); len(elem) >= l && elem[0:l] == "lm" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleLLMGetRequest([0]string{}, elemIsEscaped, w, r)
						case "PUT":
							s.handleLLMUpdateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn27AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'o': // Prefix: "ocation/"

					if l := len("ocation/"); len(elem) >= l && elem[0:l] == "ocation/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "devices"
						origElem := elem
						if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleLocationListDevicesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleLocationDeleteDeviceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleLocationUpdateDeviceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,PUT",
										allowedHeaders: rn32AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 'p': // Prefix: "places"
						origElem := elem
						if l := len("places"); len(elem) >= l && elem[0:l] == "places" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleLocationListPlacesRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleLocationCreatePlaceRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn29AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleLocationDeletePlaceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleLocationUpdatePlaceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,PUT",
										allowedHeaders: rn34AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					}
					// Param: "userId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleLocationUserLocationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'm': // Prefix: "mories"

					if l := len("mories"); len(elem) >= l && elem[0:l] == "mories" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleMemoriesListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleMemoriesCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn37AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "duplicates"
							origElem := elem
							if l := len("duplicates"); len(elem) >= l && elem[0:l] == "duplicates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleMemoriesDuplicatesRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

							elem = origElem
						case 'v': // Prefix: "vec-stats"
							origElem := elem
							if l := len("vec-stats"); len(elem) >= l && elem[0:l] == "vec-stats" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleMemoriesVecStatsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

							elem = origElem
						case 'w': // Prefix: "with-vec"
							origElem := elem
							if l := len("with-vec"); len(elem) >= l && elem[0:l] == "with-vec" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleMemoriesListWithVecRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

							elem = origElem
						}
						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleMemoriesDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleMemoriesGetRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleMemoriesUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PUT",
									allowedHeaders: rn39AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 't': // Prefix: "trics/json"

					if l := len("trics/json"); len(elem) >= l && elem[0:l] == "trics/json" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleMetricsJSONRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'p': // Prefix: "prompts"

				if l := len("prompts"); len(elem) >= l && elem[0:l] == "prompts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handlePromptsListRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "name"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handlePromptsGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handlePromptsUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn46AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 's': // Prefix: "scheduled-actions"

				if l := len("scheduled-actions"); len(elem) >= l && elem[0:l] == "scheduled-actions" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleScheduledActionsListRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleScheduledActionsCreateRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn48AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleScheduledActionsDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleScheduledActionsUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PUT",
								allowedHeaders: rn50AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 't': // Prefix: "tools"

				if l := len("tools"); len(elem) >= l && elem[0:l] == "tools" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleToolsListRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "name"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/enabled"

						if l := len("/enabled"); len(elem) >= l && elem[0:l] == "/enabled" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "PUT":
								s.handleToolsSetEnabledRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "PUT",
									allowedHeaders: rn54AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleUsersListRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleUsersGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUsersUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PUT",
								allowedHeaders: rn56AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "guilds"

							if l := len("guilds"); len(elem) >= l && elem[0:l] == "guilds" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleUsersGuildsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'm': // Prefix: "memories"

							if l := len("memories"); len(elem) >= l && elem[0:l] == "memories" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleUsersMemoriesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agent/compact"

				if l := len("agent/compact"); len(elem) >= l && elem[0:l] == "agent/compact" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = AgentCompactOperation
						r.summary = ""
						r.operationID = "Agent_compact"
						r.operationGroup = ""
						r.pathPattern = "/api/agent/compact"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'b': // Prefix: "boredom"

				if l := len("boredom"); len(elem) >= l && elem[0:l] == "boredom" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = BoredomGetOperation
						r.summary = ""
						r.operationID = "Boredom_get"
						r.operationGroup = ""
						r.pathPattern = "/api/boredom"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'h': // Prefix: "hannel"

					if l := len("hannel"); len(elem) >= l && elem[0:l] == "hannel" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '-': // Prefix: "-settings"

						if l := len("-settings"); len(elem) >= l && elem[0:l] == "-settings" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ChannelSettingsListOperation
								r.summary = ""
								r.operationID = "ChannelSettings_list"
								r.operationGroup = ""
								r.pathPattern = "/api/channel-settings"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "channelId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = ChannelSettingsDeleteOperation
									r.summary = ""
									r.operationID = "ChannelSettings_delete"
									r.operationGroup = ""
									r.pathPattern = "/api/channel-settings/{channelId}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = ChannelSettingsUpdateOperation
									r.summary = ""
									r.operationID = "ChannelSettings_update"
									r.operationGroup = ""
									r.pathPattern = "/api/channel-settings/{channelId}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 's': // Prefix: "s"

						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ChannelsListOperation
								r.summary = ""
								r.operationID = "Channels_list"
								r.operationGroup = ""
								r.pathPattern = "/api/channels"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'o': // Prefix: "on"

					if l := len("on"); len(elem) >= l && elem[0:l] == "on" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 't': // Prefix: "text"

						if l := len("text"); len(elem) >= l && elem[0:l] == "text" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ContextGetOperation
								r.summary = ""
								r.operationID = "Context_get"
								r.operationGroup = ""
								r.pathPattern = "/api/context"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'v': // Prefix: "versation-logs"

						if l := len("versation-logs"); len(elem) >= l && elem[0:l] == "versation-logs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ConversationLogsListOperation
								r.summary = ""
								r.operationID = "ConversationLogs_list"
								r.operationGroup = ""
								r.pathPattern = "/api/conversation-logs"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/export"

							if l := len("/export"); len(elem) >= l && elem[0:l] == "/export" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ConversationLogsExportOperation
									r.summary = ""
									r.operationID = "ConversationLogs_export"
									r.operationGroup = ""
									r.pathPattern = "/api/conversation-logs/export"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'd': // Prefix: "diary"

				if l := len("diary"); len(elem) >= l && elem[0:l] == "diary" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = DiaryListOperation
						r.summary = ""
						r.operationID = "Diary_list"
						r.operationGroup = ""
						r.pathPattern = "/api/diary"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'f': // Prefix: "forget/"

				if l := len("forget/"); len(elem) >= l && elem[0:l] == "forget/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "delete"

					if l := len("delete"); len(elem) >= l && elem[0:l] == "delete" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ForgetDeleteOperation
							r.summary = ""
							r.operationID = "Forget_delete"
							r.operationGroup = ""
							r.pathPattern = "/api/forget/delete"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'g': // Prefix: "groups"

					if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ForgetGroupsOperation
							r.summary = ""
							r.operationID = "Forget_groups"
							r.operationGroup = ""
							r.pathPattern = "/api/forget/groups"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'm': // Prefix: "merge"

					if l := len("merge"); len(elem) >= l && elem[0:l] == "merge" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ForgetMergeOperation
							r.summary = ""
							r.operationID = "Forget_merge"
							r.operationGroup = ""
							r.pathPattern = "/api/forget/merge"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "run"

					if l := len("run"); len(elem) >= l && elem[0:l] == "run" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ForgetRunOperation
							r.summary = ""
							r.operationID = "Forget_run"
							r.operationGroup = ""
							r.pathPattern = "/api/forget/run"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "status"

					if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ForgetStatusOperation
							r.summary = ""
							r.operationID = "Forget_status"
							r.operationGroup = ""
							r.pathPattern = "/api/forget/status"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'g': // Prefix: "guilds"

				if l := len("guilds"); len(elem) >= l && elem[0:l] == "guilds" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = GuildsListOperation
						r.summary = ""
						r.operationID = "Guilds_list"
						r.operationGroup = ""
						r.pathPattern = "/api/guilds"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/channels"

						if l := len("/channels"); len(elem) >= l && elem[0:l] == "/channels" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GuildsChannelsOperation
								r.summary = ""
								r.operationID = "Guilds_channels"
								r.operationGroup = ""
								r.pathPattern = "/api/guilds/{id}/channels"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'h': // Prefix: "health"

				if l := len("health"); len(elem) >= l && elem[0:l] == "health" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = HealthCheckOperation
						r.summary = ""
						r.operationID = "Health_check"
						r.operationGroup = ""
						r.pathPattern = "/api/health"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'i': // Prefix: "identity"

				if l := len("identity"); len(elem) >= l && elem[0:l] == "identity" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = IdentityGetOperation
						r.summary = ""
						r.operationID = "Identity_get"
						r.operationGroup = ""
						r.pathPattern = "/api/identity"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'l': // Prefix: "l"

				if l := len("l"); len(elem) >= l && elem[0:l] == "l" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "lm"

					if l := len("lm"); len(elem) >= l && elem[0:l] == "lm" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = LLMGetOperation
							r.summary = ""
							r.operationID = "LLM_get"
							r.operationGroup = ""
							r.pathPattern = "/api/llm"
							r.args = args
							r.count = 0
							return r, true
						case "PUT":
							r.name = LLMUpdateOperation
							r.summary = ""
							r.operationID = "LLM_update"
							r.operationGroup = ""
							r.pathPattern = "/api/llm"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'o': // Prefix: "ocation/"

					if l := len("ocation/"); len(elem) >= l && elem[0:l] == "ocation/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "devices"
						origElem := elem
						if l := len("devices"); len(elem) >= l && elem[0:l] == "devices" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = LocationListDevicesOperation
								r.summary = ""
								r.operationID = "Location_listDevices"
								r.operationGroup = ""
								r.pathPattern = "/api/location/devices"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = LocationDeleteDeviceOperation
									r.summary = ""
									r.operationID = "Location_deleteDevice"
									r.operationGroup = ""
									r.pathPattern = "/api/location/devices/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = LocationUpdateDeviceOperation
									r.summary = ""
									r.operationID = "Location_updateDevice"
									r.operationGroup = ""
									r.pathPattern = "/api/location/devices/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 'p': // Prefix: "places"
						origElem := elem
						if l := len("places"); len(elem) >= l && elem[0:l] == "places" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = LocationListPlacesOperation
								r.summary = ""
								r.operationID = "Location_listPlaces"
								r.operationGroup = ""
								r.pathPattern = "/api/location/places"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = LocationCreatePlaceOperation
								r.summary = ""
								r.operationID = "Location_createPlace"
								r.operationGroup = ""
								r.pathPattern = "/api/location/places"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = LocationDeletePlaceOperation
									r.summary = ""
									r.operationID = "Location_deletePlace"
									r.operationGroup = ""
									r.pathPattern = "/api/location/places/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = LocationUpdatePlaceOperation
									r.summary = ""
									r.operationID = "Location_updatePlace"
									r.operationGroup = ""
									r.pathPattern = "/api/location/places/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					}
					// Param: "userId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = LocationUserLocationOperation
							r.summary = ""
							r.operationID = "Location_userLocation"
							r.operationGroup = ""
							r.pathPattern = "/api/location/{userId}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'm': // Prefix: "mories"

					if l := len("mories"); len(elem) >= l && elem[0:l] == "mories" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = MemoriesListOperation
							r.summary = ""
							r.operationID = "Memories_list"
							r.operationGroup = ""
							r.pathPattern = "/api/memories"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = MemoriesCreateOperation
							r.summary = ""
							r.operationID = "Memories_create"
							r.operationGroup = ""
							r.pathPattern = "/api/memories"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "duplicates"
							origElem := elem
							if l := len("duplicates"); len(elem) >= l && elem[0:l] == "duplicates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = MemoriesDuplicatesOperation
									r.summary = ""
									r.operationID = "Memories_duplicates"
									r.operationGroup = ""
									r.pathPattern = "/api/memories/duplicates"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'v': // Prefix: "vec-stats"
							origElem := elem
							if l := len("vec-stats"); len(elem) >= l && elem[0:l] == "vec-stats" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = MemoriesVecStatsOperation
									r.summary = ""
									r.operationID = "Memories_vecStats"
									r.operationGroup = ""
									r.pathPattern = "/api/memories/vec-stats"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'w': // Prefix: "with-vec"
							origElem := elem
							if l := len("with-vec"); len(elem) >= l && elem[0:l] == "with-vec" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = MemoriesListWithVecOperation
									r.summary = ""
									r.operationID = "Memories_listWithVec"
									r.operationGroup = ""
									r.pathPattern = "/api/memories/with-vec"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}
						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = MemoriesDeleteOperation
								r.summary = ""
								r.operationID = "Memories_delete"
								r.operationGroup = ""
								r.pathPattern = "/api/memories/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = MemoriesGetOperation
								r.summary = ""
								r.operationID = "Memories_get"
								r.operationGroup = ""
								r.pathPattern = "/api/memories/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = MemoriesUpdateOperation
								r.summary = ""
								r.operationID = "Memories_update"
								r.operationGroup = ""
								r.pathPattern = "/api/memories/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 't': // Prefix: "trics/json"

					if l := len("trics/json"); len(elem) >= l && elem[0:l] == "trics/json" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = MetricsJSONOperation
							r.summary = ""
							r.operationID = "Metrics_json"
							r.operationGroup = ""
							r.pathPattern = "/api/metrics/json"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'p': // Prefix: "prompts"

				if l := len("prompts"); len(elem) >= l && elem[0:l] == "prompts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = PromptsListOperation
						r.summary = ""
						r.operationID = "Prompts_list"
						r.operationGroup = ""
						r.pathPattern = "/api/prompts"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "name"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = PromptsGetOperation
							r.summary = ""
							r.operationID = "Prompts_get"
							r.operationGroup = ""
							r.pathPattern = "/api/prompts/{name}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = PromptsUpdateOperation
							r.summary = ""
							r.operationID = "Prompts_update"
							r.operationGroup = ""
							r.pathPattern = "/api/prompts/{name}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 's': // Prefix: "scheduled-actions"

				if l := len("scheduled-actions"); len(elem) >= l && elem[0:l] == "scheduled-actions" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ScheduledActionsListOperation
						r.summary = ""
						r.operationID = "ScheduledActions_list"
						r.operationGroup = ""
						r.pathPattern = "/api/scheduled-actions"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = ScheduledActionsCreateOperation
						r.summary = ""
						r.operationID = "ScheduledActions_create"
						r.operationGroup = ""
						r.pathPattern = "/api/scheduled-actions"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = ScheduledActionsDeleteOperation
							r.summary = ""
							r.operationID = "ScheduledActions_delete"
							r.operationGroup = ""
							r.pathPattern = "/api/scheduled-actions/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = ScheduledActionsUpdateOperation
							r.summary = ""
							r.operationID = "ScheduledActions_update"
							r.operationGroup = ""
							r.pathPattern = "/api/scheduled-actions/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 't': // Prefix: "tools"

				if l := len("tools"); len(elem) >= l && elem[0:l] == "tools" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ToolsListOperation
						r.summary = ""
						r.operationID = "Tools_list"
						r.operationGroup = ""
						r.pathPattern = "/api/tools"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "name"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/enabled"

						if l := len("/enabled"); len(elem) >= l && elem[0:l] == "/enabled" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "PUT":
								r.name = ToolsSetEnabledOperation
								r.summary = ""
								r.operationID = "Tools_setEnabled"
								r.operationGroup = ""
								r.pathPattern = "/api/tools/{name}/enabled"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = UsersListOperation
						r.summary = ""
						r.operationID = "Users_list"
						r.operationGroup = ""
						r.pathPattern = "/api/users"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = UsersGetOperation
							r.summary = ""
							r.operationID = "Users_get"
							r.operationGroup = ""
							r.pathPattern = "/api/users/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UsersUpdateOperation
							r.summary = ""
							r.operationID = "Users_update"
							r.operationGroup = ""
							r.pathPattern = "/api/users/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "guilds"

							if l := len("guilds"); len(elem) >= l && elem[0:l] == "guilds" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = UsersGuildsOperation
									r.summary = ""
									r.operationID = "Users_guilds"
									r.operationGroup = ""
									r.pathPattern = "/api/users/{id}/guilds"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'm': // Prefix: "memories"

							if l := len("memories"); len(elem) >= l && elem[0:l] == "memories" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = UsersMemoriesOperation
									r.summary = ""
									r.operationID = "Users_memories"
									r.operationGroup = ""
									r.pathPattern = "/api/users/{id}/memories"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
