// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/go-faster/jx"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AgentCompact implements Agent_compact operation.
	//
	// POST /api/agent/compact
	AgentCompact(ctx context.Context) (jx.Raw, error)
	// BoredomGet implements Boredom_get operation.
	//
	// GET /api/boredom
	BoredomGet(ctx context.Context) (*BoredomStatus, error)
	// ChannelSettingsDelete implements ChannelSettings_delete operation.
	//
	// DELETE /api/channel-settings/{channelId}
	ChannelSettingsDelete(ctx context.Context, params ChannelSettingsDeleteParams) error
	// ChannelSettingsList implements ChannelSettings_list operation.
	//
	// GET /api/channel-settings
	ChannelSettingsList(ctx context.Context, params ChannelSettingsListParams) (*ChannelSettingsListOK, error)
	// ChannelSettingsUpdate implements ChannelSettings_update operation.
	//
	// PUT /api/channel-settings/{channelId}
	ChannelSettingsUpdate(ctx context.Context, req *UpdateChannelSettingRequest, params ChannelSettingsUpdateParams) (*OkResponse, error)
	// ChannelsList implements Channels_list operation.
	//
	// GET /api/channels
	ChannelsList(ctx context.Context) (*ChannelsListOK, error)
	// ContextGet implements Context_get operation.
	//
	// GET /api/context
	ContextGet(ctx context.Context, params ContextGetParams) (jx.Raw, error)
	// ConversationLogsExport implements ConversationLogs_export operation.
	//
	// Export as JSONL.
	//
	// GET /api/conversation-logs/export
	ConversationLogsExport(ctx context.Context, params ConversationLogsExportParams) (ConversationLogsExportOK, error)
	// ConversationLogsList implements ConversationLogs_list operation.
	//
	// GET /api/conversation-logs
	ConversationLogsList(ctx context.Context) (*ConversationLogsListOK, error)
	// DiaryList implements Diary_list operation.
	//
	// GET /api/diary
	DiaryList(ctx context.Context, params DiaryListParams) (*DiaryListOK, error)
	// ForgetDelete implements Forget_delete operation.
	//
	// POST /api/forget/delete
	ForgetDelete(ctx context.Context, req *ForgetDeleteRequest) (*ForgetDeleteOK, error)
	// ForgetGroups implements Forget_groups operation.
	//
	// GET /api/forget/groups
	ForgetGroups(ctx context.Context, params ForgetGroupsParams) (*ForgetGroupsOK, error)
	// ForgetMerge implements Forget_merge operation.
	//
	// POST /api/forget/merge
	ForgetMerge(ctx context.Context, req *ForgetMergeRequest) (*ForgetMergeOK, error)
	// ForgetRun implements Forget_run operation.
	//
	// POST /api/forget/run
	ForgetRun(ctx context.Context, req OptForgetRunReq) (jx.Raw, error)
	// ForgetStatus implements Forget_status operation.
	//
	// GET /api/forget/status
	ForgetStatus(ctx context.Context) (jx.Raw, error)
	// GuildsChannels implements Guilds_channels operation.
	//
	// GET /api/guilds/{id}/channels
	GuildsChannels(ctx context.Context, params GuildsChannelsParams) (*GuildsChannelsOK, error)
	// GuildsList implements Guilds_list operation.
	//
	// GET /api/guilds
	GuildsList(ctx context.Context) (*GuildsListOK, error)
	// HealthCheck implements Health_check operation.
	//
	// GET /api/health
	HealthCheck(ctx context.Context) (*HealthCheckOK, error)
	// IdentityGet implements Identity_get operation.
	//
	// GET /api/identity
	IdentityGet(ctx context.Context) (jx.Raw, error)
	// LLMGet implements LLM_get operation.
	//
	// GET /api/llm
	LLMGet(ctx context.Context) (jx.Raw, error)
	// LLMUpdate implements LLM_update operation.
	//
	// PUT /api/llm
	LLMUpdate(ctx context.Context, req jx.Raw) (jx.Raw, error)
	// LocationCreatePlace implements Location_createPlace operation.
	//
	// POST /api/location/places
	LocationCreatePlace(ctx context.Context, req *CreatePlaceRequest) (*OkResponse, error)
	// LocationDeleteDevice implements Location_deleteDevice operation.
	//
	// DELETE /api/location/devices/{id}
	LocationDeleteDevice(ctx context.Context, params LocationDeleteDeviceParams) error
	// LocationDeletePlace implements Location_deletePlace operation.
	//
	// DELETE /api/location/places/{id}
	LocationDeletePlace(ctx context.Context, params LocationDeletePlaceParams) error
	// LocationListDevices implements Location_listDevices operation.
	//
	// GET /api/location/devices
	LocationListDevices(ctx context.Context) (*LocationListDevicesOK, error)
	// LocationListPlaces implements Location_listPlaces operation.
	//
	// GET /api/location/places
	LocationListPlaces(ctx context.Context) (*LocationListPlacesOK, error)
	// LocationUpdateDevice implements Location_updateDevice operation.
	//
	// PUT /api/location/devices/{id}
	LocationUpdateDevice(ctx context.Context, req *UpdateDeviceRequest, params LocationUpdateDeviceParams) (*OkResponse, error)
	// LocationUpdatePlace implements Location_updatePlace operation.
	//
	// PUT /api/location/places/{id}
	LocationUpdatePlace(ctx context.Context, req *UpdatePlaceRequest, params LocationUpdatePlaceParams) (*OkResponse, error)
	// LocationUserLocation implements Location_userLocation operation.
	//
	// GET /api/location/{userId}
	LocationUserLocation(ctx context.Context, params LocationUserLocationParams) (*LocationUserLocationOK, error)
	// MemoriesCreate implements Memories_create operation.
	//
	// POST /api/memories
	MemoriesCreate(ctx context.Context, req *CreateMemoryRequest) (*MemoriesCreateCreated, error)
	// MemoriesDelete implements Memories_delete operation.
	//
	// DELETE /api/memories/{id}
	MemoriesDelete(ctx context.Context, params MemoriesDeleteParams) error
	// MemoriesDuplicates implements Memories_duplicates operation.
	//
	// GET /api/memories/duplicates
	MemoriesDuplicates(ctx context.Context, params MemoriesDuplicatesParams) (*MemoriesDuplicatesOK, error)
	// MemoriesGet implements Memories_get operation.
	//
	// GET /api/memories/{id}
	MemoriesGet(ctx context.Context, params MemoriesGetParams) (*MemoriesGetOK, error)
	// MemoriesList implements Memories_list operation.
	//
	// GET /api/memories
	MemoriesList(ctx context.Context, params MemoriesListParams) (*MemoriesListOK, error)
	// MemoriesListWithVec implements Memories_listWithVec operation.
	//
	// GET /api/memories/with-vec
	MemoriesListWithVec(ctx context.Context, params MemoriesListWithVecParams) (*MemoriesListWithVecOK, error)
	// MemoriesUpdate implements Memories_update operation.
	//
	// PUT /api/memories/{id}
	MemoriesUpdate(ctx context.Context, req *UpdateMemoryRequest, params MemoriesUpdateParams) (*MemoriesUpdateOK, error)
	// MemoriesVecStats implements Memories_vecStats operation.
	//
	// GET /api/memories/vec-stats
	MemoriesVecStats(ctx context.Context) (*VecStats, error)
	// MetricsJSON implements Metrics_json operation.
	//
	// GET /api/metrics/json
	MetricsJSON(ctx context.Context) (*MetricsJSONOK, error)
	// PromptsGet implements Prompts_get operation.
	//
	// GET /api/prompts/{name}
	PromptsGet(ctx context.Context, params PromptsGetParams) (*PromptFile, error)
	// PromptsList implements Prompts_list operation.
	//
	// GET /api/prompts
	PromptsList(ctx context.Context) ([]PromptFile, error)
	// PromptsUpdate implements Prompts_update operation.
	//
	// PUT /api/prompts/{name}
	PromptsUpdate(ctx context.Context, req *UpdatePromptRequest, params PromptsUpdateParams) (*PromptsUpdateOK, error)
	// ScheduledActionsCreate implements ScheduledActions_create operation.
	//
	// POST /api/scheduled-actions
	ScheduledActionsCreate(ctx context.Context, req *CreateActionRequest) (*ScheduledActionsCreateCreated, error)
	// ScheduledActionsDelete implements ScheduledActions_delete operation.
	//
	// DELETE /api/scheduled-actions/{id}
	ScheduledActionsDelete(ctx context.Context, params ScheduledActionsDeleteParams) (*OkResponse, error)
	// ScheduledActionsList implements ScheduledActions_list operation.
	//
	// GET /api/scheduled-actions
	ScheduledActionsList(ctx context.Context, params ScheduledActionsListParams) (*ScheduledActionsListOK, error)
	// ScheduledActionsUpdate implements ScheduledActions_update operation.
	//
	// PUT /api/scheduled-actions/{id}
	ScheduledActionsUpdate(ctx context.Context, req *UpdateActionRequest, params ScheduledActionsUpdateParams) (*OkResponse, error)
	// ToolsList implements Tools_list operation.
	//
	// GET /api/tools
	ToolsList(ctx context.Context) (jx.Raw, error)
	// ToolsSetEnabled implements Tools_setEnabled operation.
	//
	// PUT /api/tools/{name}/enabled
	ToolsSetEnabled(ctx context.Context, req jx.Raw, params ToolsSetEnabledParams) (jx.Raw, error)
	// UsersGet implements Users_get operation.
	//
	// GET /api/users/{id}
	UsersGet(ctx context.Context, params UsersGetParams) (*UsersGetOK, error)
	// UsersGuilds implements Users_guilds operation.
	//
	// GET /api/users/{id}/guilds
	UsersGuilds(ctx context.Context, params UsersGuildsParams) (*UsersGuildsOK, error)
	// UsersList implements Users_list operation.
	//
	// GET /api/users
	UsersList(ctx context.Context, params UsersListParams) (*UsersListOK, error)
	// UsersMemories implements Users_memories operation.
	//
	// GET /api/users/{id}/memories
	UsersMemories(ctx context.Context, params UsersMemoriesParams) (*UsersMemoriesOK, error)
	// UsersUpdate implements Users_update operation.
	//
	// PUT /api/users/{id}
	UsersUpdate(ctx context.Context, req *UpdateUserRequest, params UsersUpdateParams) (*OkResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
