// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AgentCompact implements Agent_compact operation.
//
// POST /api/agent/compact
func (UnimplementedHandler) AgentCompact(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// BoredomGet implements Boredom_get operation.
//
// GET /api/boredom
func (UnimplementedHandler) BoredomGet(ctx context.Context) (r *BoredomStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// ChannelSettingsDelete implements ChannelSettings_delete operation.
//
// DELETE /api/channel-settings/{channelId}
func (UnimplementedHandler) ChannelSettingsDelete(ctx context.Context, params ChannelSettingsDeleteParams) error {
	return ht.ErrNotImplemented
}

// ChannelSettingsList implements ChannelSettings_list operation.
//
// GET /api/channel-settings
func (UnimplementedHandler) ChannelSettingsList(ctx context.Context, params ChannelSettingsListParams) (r *ChannelSettingsListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ChannelSettingsUpdate implements ChannelSettings_update operation.
//
// PUT /api/channel-settings/{channelId}
func (UnimplementedHandler) ChannelSettingsUpdate(ctx context.Context, req *UpdateChannelSettingRequest, params ChannelSettingsUpdateParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ChannelsList implements Channels_list operation.
//
// GET /api/channels
func (UnimplementedHandler) ChannelsList(ctx context.Context) (r *ChannelsListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ContextGet implements Context_get operation.
//
// GET /api/context
func (UnimplementedHandler) ContextGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// ConversationLogsExport implements ConversationLogs_export operation.
//
// Export as JSONL.
//
// GET /api/conversation-logs/export
func (UnimplementedHandler) ConversationLogsExport(ctx context.Context, params ConversationLogsExportParams) (r ConversationLogsExportOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ConversationLogsList implements ConversationLogs_list operation.
//
// GET /api/conversation-logs
func (UnimplementedHandler) ConversationLogsList(ctx context.Context) (r *ConversationLogsListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ForgetDelete implements Forget_delete operation.
//
// POST /api/forget/delete
func (UnimplementedHandler) ForgetDelete(ctx context.Context, req *ForgetDeleteRequest) (r *ForgetDeleteOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ForgetGroups implements Forget_groups operation.
//
// GET /api/forget/groups
func (UnimplementedHandler) ForgetGroups(ctx context.Context, params ForgetGroupsParams) (r *ForgetGroupsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ForgetMerge implements Forget_merge operation.
//
// POST /api/forget/merge
func (UnimplementedHandler) ForgetMerge(ctx context.Context, req *ForgetMergeRequest) (r *ForgetMergeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ForgetRun implements Forget_run operation.
//
// POST /api/forget/run
func (UnimplementedHandler) ForgetRun(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// ForgetStatus implements Forget_status operation.
//
// GET /api/forget/status
func (UnimplementedHandler) ForgetStatus(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// GuildsChannels implements Guilds_channels operation.
//
// GET /api/guilds/{id}/channels
func (UnimplementedHandler) GuildsChannels(ctx context.Context, params GuildsChannelsParams) (r *GuildsChannelsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GuildsList implements Guilds_list operation.
//
// GET /api/guilds
func (UnimplementedHandler) GuildsList(ctx context.Context) (r *GuildsListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements Health_check operation.
//
// GET /api/health
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r *HealthCheckOK, _ error) {
	return r, ht.ErrNotImplemented
}

// IdentityGet implements Identity_get operation.
//
// GET /api/identity
func (UnimplementedHandler) IdentityGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// LLMGet implements LLM_get operation.
//
// GET /api/llm
func (UnimplementedHandler) LLMGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// LLMUpdate implements LLM_update operation.
//
// PUT /api/llm
func (UnimplementedHandler) LLMUpdate(ctx context.Context, req jx.Raw) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationCreatePlace implements Location_createPlace operation.
//
// POST /api/location/places
func (UnimplementedHandler) LocationCreatePlace(ctx context.Context, req *CreatePlaceRequest) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationDeleteDevice implements Location_deleteDevice operation.
//
// DELETE /api/location/devices/{id}
func (UnimplementedHandler) LocationDeleteDevice(ctx context.Context, params LocationDeleteDeviceParams) error {
	return ht.ErrNotImplemented
}

// LocationDeletePlace implements Location_deletePlace operation.
//
// DELETE /api/location/places/{id}
func (UnimplementedHandler) LocationDeletePlace(ctx context.Context, params LocationDeletePlaceParams) error {
	return ht.ErrNotImplemented
}

// LocationListDevices implements Location_listDevices operation.
//
// GET /api/location/devices
func (UnimplementedHandler) LocationListDevices(ctx context.Context) (r *LocationListDevicesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationListPlaces implements Location_listPlaces operation.
//
// GET /api/location/places
func (UnimplementedHandler) LocationListPlaces(ctx context.Context) (r *LocationListPlacesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationUpdateDevice implements Location_updateDevice operation.
//
// PUT /api/location/devices/{id}
func (UnimplementedHandler) LocationUpdateDevice(ctx context.Context, req *UpdateDeviceRequest, params LocationUpdateDeviceParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationUpdatePlace implements Location_updatePlace operation.
//
// PUT /api/location/places/{id}
func (UnimplementedHandler) LocationUpdatePlace(ctx context.Context, req *UpdatePlaceRequest, params LocationUpdatePlaceParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// LocationUserLocation implements Location_userLocation operation.
//
// GET /api/location/{userId}
func (UnimplementedHandler) LocationUserLocation(ctx context.Context, params LocationUserLocationParams) (r *LocationUserLocationOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesCreate implements Memories_create operation.
//
// POST /api/memories
func (UnimplementedHandler) MemoriesCreate(ctx context.Context, req *CreateMemoryRequest) (r *MemoriesCreateCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesDelete implements Memories_delete operation.
//
// DELETE /api/memories/{id}
func (UnimplementedHandler) MemoriesDelete(ctx context.Context, params MemoriesDeleteParams) error {
	return ht.ErrNotImplemented
}

// MemoriesDuplicates implements Memories_duplicates operation.
//
// GET /api/memories/duplicates
func (UnimplementedHandler) MemoriesDuplicates(ctx context.Context, params MemoriesDuplicatesParams) (r *MemoriesDuplicatesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesGet implements Memories_get operation.
//
// GET /api/memories/{id}
func (UnimplementedHandler) MemoriesGet(ctx context.Context, params MemoriesGetParams) (r *MemoriesGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesList implements Memories_list operation.
//
// GET /api/memories
func (UnimplementedHandler) MemoriesList(ctx context.Context, params MemoriesListParams) (r *MemoriesListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesListWithVec implements Memories_listWithVec operation.
//
// GET /api/memories/with-vec
func (UnimplementedHandler) MemoriesListWithVec(ctx context.Context, params MemoriesListWithVecParams) (r *MemoriesListWithVecOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesUpdate implements Memories_update operation.
//
// PUT /api/memories/{id}
func (UnimplementedHandler) MemoriesUpdate(ctx context.Context, req *UpdateMemoryRequest, params MemoriesUpdateParams) (r *MemoriesUpdateOK, _ error) {
	return r, ht.ErrNotImplemented
}

// MemoriesVecStats implements Memories_vecStats operation.
//
// GET /api/memories/vec-stats
func (UnimplementedHandler) MemoriesVecStats(ctx context.Context) (r *VecStats, _ error) {
	return r, ht.ErrNotImplemented
}

// MetricsJSON implements Metrics_json operation.
//
// GET /api/metrics/json
func (UnimplementedHandler) MetricsJSON(ctx context.Context) (r *MetricsJSONOK, _ error) {
	return r, ht.ErrNotImplemented
}

// PlaygroundChat implements Playground_chat operation.
//
// POST /api/playground
func (UnimplementedHandler) PlaygroundChat(ctx context.Context, req jx.Raw) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// PromptsGet implements Prompts_get operation.
//
// GET /api/prompts/{name}
func (UnimplementedHandler) PromptsGet(ctx context.Context, params PromptsGetParams) (r *PromptFile, _ error) {
	return r, ht.ErrNotImplemented
}

// PromptsList implements Prompts_list operation.
//
// GET /api/prompts
func (UnimplementedHandler) PromptsList(ctx context.Context) (r []PromptFile, _ error) {
	return r, ht.ErrNotImplemented
}

// PromptsUpdate implements Prompts_update operation.
//
// PUT /api/prompts/{name}
func (UnimplementedHandler) PromptsUpdate(ctx context.Context, req *UpdatePromptRequest, params PromptsUpdateParams) (r *PromptsUpdateOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ScheduledActionsCreate implements ScheduledActions_create operation.
//
// POST /api/scheduled-actions
func (UnimplementedHandler) ScheduledActionsCreate(ctx context.Context, req *CreateActionRequest) (r *ScheduledActionsCreateCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// ScheduledActionsDelete implements ScheduledActions_delete operation.
//
// DELETE /api/scheduled-actions/{id}
func (UnimplementedHandler) ScheduledActionsDelete(ctx context.Context, params ScheduledActionsDeleteParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ScheduledActionsList implements ScheduledActions_list operation.
//
// GET /api/scheduled-actions
func (UnimplementedHandler) ScheduledActionsList(ctx context.Context, params ScheduledActionsListParams) (r *ScheduledActionsListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ScheduledActionsUpdate implements ScheduledActions_update operation.
//
// PUT /api/scheduled-actions/{id}
func (UnimplementedHandler) ScheduledActionsUpdate(ctx context.Context, req *UpdateActionRequest, params ScheduledActionsUpdateParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ToolsList implements Tools_list operation.
//
// GET /api/tools
func (UnimplementedHandler) ToolsList(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// ToolsSetEnabled implements Tools_setEnabled operation.
//
// PUT /api/tools/{name}/enabled
func (UnimplementedHandler) ToolsSetEnabled(ctx context.Context, req jx.Raw, params ToolsSetEnabledParams) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGet implements Users_get operation.
//
// GET /api/users/{id}
func (UnimplementedHandler) UsersGet(ctx context.Context, params UsersGetParams) (r *UsersGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGuilds implements Users_guilds operation.
//
// GET /api/users/{id}/guilds
func (UnimplementedHandler) UsersGuilds(ctx context.Context, params UsersGuildsParams) (r *UsersGuildsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersList implements Users_list operation.
//
// GET /api/users
func (UnimplementedHandler) UsersList(ctx context.Context, params UsersListParams) (r *UsersListOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersMemories implements Users_memories operation.
//
// GET /api/users/{id}/memories
func (UnimplementedHandler) UsersMemories(ctx context.Context, params UsersMemoriesParams) (r *UsersMemoriesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUpdate implements Users_update operation.
//
// PUT /api/users/{id}
func (UnimplementedHandler) UsersUpdate(ctx context.Context, req *UpdateUserRequest, params UsersUpdateParams) (r *OkResponse, _ error) {
	return r, ht.ErrNotImplemented
}
