// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/BoredomStatus
type BoredomStatus struct {
	Boredom         float64   `json:"boredom"`
	LastInteraction OptString `json:"last_interaction"`
	LastChannel     string    `json:"last_channel"`
	LastPostedAt    OptString `json:"last_posted_at"`
	PostThreshold   float64   `json:"post_threshold"`
}

// GetBoredom returns the value of Boredom.
func (s *BoredomStatus) GetBoredom() float64 {
	return s.Boredom
}

// GetLastInteraction returns the value of LastInteraction.
func (s *BoredomStatus) GetLastInteraction() OptString {
	return s.LastInteraction
}

// GetLastChannel returns the value of LastChannel.
func (s *BoredomStatus) GetLastChannel() string {
	return s.LastChannel
}

// GetLastPostedAt returns the value of LastPostedAt.
func (s *BoredomStatus) GetLastPostedAt() OptString {
	return s.LastPostedAt
}

// GetPostThreshold returns the value of PostThreshold.
func (s *BoredomStatus) GetPostThreshold() float64 {
	return s.PostThreshold
}

// SetBoredom sets the value of Boredom.
func (s *BoredomStatus) SetBoredom(val float64) {
	s.Boredom = val
}

// SetLastInteraction sets the value of LastInteraction.
func (s *BoredomStatus) SetLastInteraction(val OptString) {
	s.LastInteraction = val
}

// SetLastChannel sets the value of LastChannel.
func (s *BoredomStatus) SetLastChannel(val string) {
	s.LastChannel = val
}

// SetLastPostedAt sets the value of LastPostedAt.
func (s *BoredomStatus) SetLastPostedAt(val OptString) {
	s.LastPostedAt = val
}

// SetPostThreshold sets the value of PostThreshold.
func (s *BoredomStatus) SetPostThreshold(val float64) {
	s.PostThreshold = val
}

// Ref: #/components/schemas/Channel
type Channel struct {
	ChannelID   string `json:"channel_id"`
	ChannelName string `json:"channel_name"`
	GuildID     string `json:"guild_id"`
	GuildName   string `json:"guild_name"`
}

// GetChannelID returns the value of ChannelID.
func (s *Channel) GetChannelID() string {
	return s.ChannelID
}

// GetChannelName returns the value of ChannelName.
func (s *Channel) GetChannelName() string {
	return s.ChannelName
}

// GetGuildID returns the value of GuildID.
func (s *Channel) GetGuildID() string {
	return s.GuildID
}

// GetGuildName returns the value of GuildName.
func (s *Channel) GetGuildName() string {
	return s.GuildName
}

// SetChannelID sets the value of ChannelID.
func (s *Channel) SetChannelID(val string) {
	s.ChannelID = val
}

// SetChannelName sets the value of ChannelName.
func (s *Channel) SetChannelName(val string) {
	s.ChannelName = val
}

// SetGuildID sets the value of GuildID.
func (s *Channel) SetGuildID(val string) {
	s.GuildID = val
}

// SetGuildName sets the value of GuildName.
func (s *Channel) SetGuildName(val string) {
	s.GuildName = val
}

// Ref: #/components/schemas/ChannelSetting
type ChannelSetting struct {
	ChannelID         string             `json:"channel_id"`
	ChannelName       string             `json:"channel_name"`
	GuildID           string             `json:"guild_id"`
	GuildName         string             `json:"guild_name"`
	UserCount         int32              `json:"user_count"`
	Mode              ChannelSettingMode `json:"mode"`
	Home              bool               `json:"home"`
	LastUserMessageAt OptString          `json:"last_user_message_at"`
	SettingsUpdatedAt OptString          `json:"settings_updated_at"`
}

// GetChannelID returns the value of ChannelID.
func (s *ChannelSetting) GetChannelID() string {
	return s.ChannelID
}

// GetChannelName returns the value of ChannelName.
func (s *ChannelSetting) GetChannelName() string {
	return s.ChannelName
}

// GetGuildID returns the value of GuildID.
func (s *ChannelSetting) GetGuildID() string {
	return s.GuildID
}

// GetGuildName returns the value of GuildName.
func (s *ChannelSetting) GetGuildName() string {
	return s.GuildName
}

// GetUserCount returns the value of UserCount.
func (s *ChannelSetting) GetUserCount() int32 {
	return s.UserCount
}

// GetMode returns the value of Mode.
func (s *ChannelSetting) GetMode() ChannelSettingMode {
	return s.Mode
}

// GetHome returns the value of Home.
func (s *ChannelSetting) GetHome() bool {
	return s.Home
}

// GetLastUserMessageAt returns the value of LastUserMessageAt.
func (s *ChannelSetting) GetLastUserMessageAt() OptString {
	return s.LastUserMessageAt
}

// GetSettingsUpdatedAt returns the value of SettingsUpdatedAt.
func (s *ChannelSetting) GetSettingsUpdatedAt() OptString {
	return s.SettingsUpdatedAt
}

// SetChannelID sets the value of ChannelID.
func (s *ChannelSetting) SetChannelID(val string) {
	s.ChannelID = val
}

// SetChannelName sets the value of ChannelName.
func (s *ChannelSetting) SetChannelName(val string) {
	s.ChannelName = val
}

// SetGuildID sets the value of GuildID.
func (s *ChannelSetting) SetGuildID(val string) {
	s.GuildID = val
}

// SetGuildName sets the value of GuildName.
func (s *ChannelSetting) SetGuildName(val string) {
	s.GuildName = val
}

// SetUserCount sets the value of UserCount.
func (s *ChannelSetting) SetUserCount(val int32) {
	s.UserCount = val
}

// SetMode sets the value of Mode.
func (s *ChannelSetting) SetMode(val ChannelSettingMode) {
	s.Mode = val
}

// SetHome sets the value of Home.
func (s *ChannelSetting) SetHome(val bool) {
	s.Home = val
}

// SetLastUserMessageAt sets the value of LastUserMessageAt.
func (s *ChannelSetting) SetLastUserMessageAt(val OptString) {
	s.LastUserMessageAt = val
}

// SetSettingsUpdatedAt sets the value of SettingsUpdatedAt.
func (s *ChannelSetting) SetSettingsUpdatedAt(val OptString) {
	s.SettingsUpdatedAt = val
}

type ChannelSettingMode string

const (
	ChannelSettingModeActive   ChannelSettingMode = "active"
	ChannelSettingModeListen   ChannelSettingMode = "listen"
	ChannelSettingModeDisabled ChannelSettingMode = "disabled"
)

// AllValues returns all ChannelSettingMode values.
func (ChannelSettingMode) AllValues() []ChannelSettingMode {
	return []ChannelSettingMode{
		ChannelSettingModeActive,
		ChannelSettingModeListen,
		ChannelSettingModeDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChannelSettingMode) MarshalText() ([]byte, error) {
	switch s {
	case ChannelSettingModeActive:
		return []byte(s), nil
	case ChannelSettingModeListen:
		return []byte(s), nil
	case ChannelSettingModeDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChannelSettingMode) UnmarshalText(data []byte) error {
	switch ChannelSettingMode(data) {
	case ChannelSettingModeActive:
		*s = ChannelSettingModeActive
		return nil
	case ChannelSettingModeListen:
		*s = ChannelSettingModeListen
		return nil
	case ChannelSettingModeDisabled:
		*s = ChannelSettingModeDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ChannelSettingsDeleteNoContent is response for ChannelSettingsDelete operation.
type ChannelSettingsDeleteNoContent struct{}

type ChannelSettingsListOK struct {
	Data []ChannelSetting `json:"data"`
}

// GetData returns the value of Data.
func (s *ChannelSettingsListOK) GetData() []ChannelSetting {
	return s.Data
}

// SetData sets the value of Data.
func (s *ChannelSettingsListOK) SetData(val []ChannelSetting) {
	s.Data = val
}

type ChannelsListOK struct {
	Data []Channel `json:"data"`
}

// GetData returns the value of Data.
func (s *ChannelsListOK) GetData() []Channel {
	return s.Data
}

// SetData sets the value of Data.
func (s *ChannelsListOK) SetData(val []Channel) {
	s.Data = val
}

type ContextGetSource string

const (
	ContextGetSourceDiscord ContextGetSource = "discord"
	ContextGetSourceDevice  ContextGetSource = "device"
	ContextGetSourceWeb     ContextGetSource = "web"
)

// AllValues returns all ContextGetSource values.
func (ContextGetSource) AllValues() []ContextGetSource {
	return []ContextGetSource{
		ContextGetSourceDiscord,
		ContextGetSourceDevice,
		ContextGetSourceWeb,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ContextGetSource) MarshalText() ([]byte, error) {
	switch s {
	case ContextGetSourceDiscord:
		return []byte(s), nil
	case ContextGetSourceDevice:
		return []byte(s), nil
	case ContextGetSourceWeb:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ContextGetSource) UnmarshalText(data []byte) error {
	switch ContextGetSource(data) {
	case ContextGetSourceDiscord:
		*s = ContextGetSourceDiscord
		return nil
	case ContextGetSourceDevice:
		*s = ContextGetSourceDevice
		return nil
	case ContextGetSourceWeb:
		*s = ContextGetSourceWeb
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ConversationLogsExportOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ConversationLogsExportOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type ConversationLogsListOK struct {
	Data []ConversationSummary `json:"data"`
}

// GetData returns the value of Data.
func (s *ConversationLogsListOK) GetData() []ConversationSummary {
	return s.Data
}

// SetData sets the value of Data.
func (s *ConversationLogsListOK) SetData(val []ConversationSummary) {
	s.Data = val
}

// Ref: #/components/schemas/ConversationSummary
type ConversationSummary struct {
	ChannelID string `json:"channel_id"`
	Messages  int32  `json:"messages"`
	Turns     int32  `json:"turns"`
	First     string `json:"first"`
	Last      string `json:"last"`
}

// GetChannelID returns the value of ChannelID.
func (s *ConversationSummary) GetChannelID() string {
	return s.ChannelID
}

// GetMessages returns the value of Messages.
func (s *ConversationSummary) GetMessages() int32 {
	return s.Messages
}

// GetTurns returns the value of Turns.
func (s *ConversationSummary) GetTurns() int32 {
	return s.Turns
}

// GetFirst returns the value of First.
func (s *ConversationSummary) GetFirst() string {
	return s.First
}

// GetLast returns the value of Last.
func (s *ConversationSummary) GetLast() string {
	return s.Last
}

// SetChannelID sets the value of ChannelID.
func (s *ConversationSummary) SetChannelID(val string) {
	s.ChannelID = val
}

// SetMessages sets the value of Messages.
func (s *ConversationSummary) SetMessages(val int32) {
	s.Messages = val
}

// SetTurns sets the value of Turns.
func (s *ConversationSummary) SetTurns(val int32) {
	s.Turns = val
}

// SetFirst sets the value of First.
func (s *ConversationSummary) SetFirst(val string) {
	s.First = val
}

// SetLast sets the value of Last.
func (s *ConversationSummary) SetLast(val string) {
	s.Last = val
}

// Ref: #/components/schemas/CreateActionRequest
type CreateActionRequest struct {
	ChannelID   string                     `json:"channel_id"`
	Content     string                     `json:"content"`
	Mode        OptCreateActionRequestMode `json:"mode"`
	ScheduledAt OptString                  `json:"scheduled_at"`
	CronExpr    OptString                  `json:"cron_expr"`
}

// GetChannelID returns the value of ChannelID.
func (s *CreateActionRequest) GetChannelID() string {
	return s.ChannelID
}

// GetContent returns the value of Content.
func (s *CreateActionRequest) GetContent() string {
	return s.Content
}

// GetMode returns the value of Mode.
func (s *CreateActionRequest) GetMode() OptCreateActionRequestMode {
	return s.Mode
}

// GetScheduledAt returns the value of ScheduledAt.
func (s *CreateActionRequest) GetScheduledAt() OptString {
	return s.ScheduledAt
}

// GetCronExpr returns the value of CronExpr.
func (s *CreateActionRequest) GetCronExpr() OptString {
	return s.CronExpr
}

// SetChannelID sets the value of ChannelID.
func (s *CreateActionRequest) SetChannelID(val string) {
	s.ChannelID = val
}

// SetContent sets the value of Content.
func (s *CreateActionRequest) SetContent(val string) {
	s.Content = val
}

// SetMode sets the value of Mode.
func (s *CreateActionRequest) SetMode(val OptCreateActionRequestMode) {
	s.Mode = val
}

// SetScheduledAt sets the value of ScheduledAt.
func (s *CreateActionRequest) SetScheduledAt(val OptString) {
	s.ScheduledAt = val
}

// SetCronExpr sets the value of CronExpr.
func (s *CreateActionRequest) SetCronExpr(val OptString) {
	s.CronExpr = val
}

type CreateActionRequestMode string

const (
	CreateActionRequestModeDirect CreateActionRequestMode = "direct"
	CreateActionRequestModePrompt CreateActionRequestMode = "prompt"
)

// AllValues returns all CreateActionRequestMode values.
func (CreateActionRequestMode) AllValues() []CreateActionRequestMode {
	return []CreateActionRequestMode{
		CreateActionRequestModeDirect,
		CreateActionRequestModePrompt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateActionRequestMode) MarshalText() ([]byte, error) {
	switch s {
	case CreateActionRequestModeDirect:
		return []byte(s), nil
	case CreateActionRequestModePrompt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateActionRequestMode) UnmarshalText(data []byte) error {
	switch CreateActionRequestMode(data) {
	case CreateActionRequestModeDirect:
		*s = CreateActionRequestModeDirect
		return nil
	case CreateActionRequestModePrompt:
		*s = CreateActionRequestModePrompt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CreateMemoryRequest
type CreateMemoryRequest struct {
	Type     string                         `json:"type"`
	Content  string                         `json:"content"`
	Metadata OptCreateMemoryRequestMetadata `json:"metadata"`
}

// GetType returns the value of Type.
func (s *CreateMemoryRequest) GetType() string {
	return s.Type
}

// GetContent returns the value of Content.
func (s *CreateMemoryRequest) GetContent() string {
	return s.Content
}

// GetMetadata returns the value of Metadata.
func (s *CreateMemoryRequest) GetMetadata() OptCreateMemoryRequestMetadata {
	return s.Metadata
}

// SetType sets the value of Type.
func (s *CreateMemoryRequest) SetType(val string) {
	s.Type = val
}

// SetContent sets the value of Content.
func (s *CreateMemoryRequest) SetContent(val string) {
	s.Content = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateMemoryRequest) SetMetadata(val OptCreateMemoryRequestMetadata) {
	s.Metadata = val
}

type CreateMemoryRequestMetadata map[string]jx.Raw

func (s *CreateMemoryRequestMetadata) init() CreateMemoryRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CreatePlaceRequest
type CreatePlaceRequest struct {
	Name      string     `json:"name"`
	Latitude  float64    `json:"latitude"`
	Longitude float64    `json:"longitude"`
	RadiusM   OptFloat64 `json:"radius_m"`
}

// GetName returns the value of Name.
func (s *CreatePlaceRequest) GetName() string {
	return s.Name
}

// GetLatitude returns the value of Latitude.
func (s *CreatePlaceRequest) GetLatitude() float64 {
	return s.Latitude
}

// GetLongitude returns the value of Longitude.
func (s *CreatePlaceRequest) GetLongitude() float64 {
	return s.Longitude
}

// GetRadiusM returns the value of RadiusM.
func (s *CreatePlaceRequest) GetRadiusM() OptFloat64 {
	return s.RadiusM
}

// SetName sets the value of Name.
func (s *CreatePlaceRequest) SetName(val string) {
	s.Name = val
}

// SetLatitude sets the value of Latitude.
func (s *CreatePlaceRequest) SetLatitude(val float64) {
	s.Latitude = val
}

// SetLongitude sets the value of Longitude.
func (s *CreatePlaceRequest) SetLongitude(val float64) {
	s.Longitude = val
}

// SetRadiusM sets the value of RadiusM.
func (s *CreatePlaceRequest) SetRadiusM(val OptFloat64) {
	s.RadiusM = val
}

// Ref: #/components/schemas/DeviceMapping
type DeviceMapping struct {
	ID        int32  `json:"id"`
	DeviceID  string `json:"device_id"`
	OwnerName string `json:"owner_name"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
}

// GetID returns the value of ID.
func (s *DeviceMapping) GetID() int32 {
	return s.ID
}

// GetDeviceID returns the value of DeviceID.
func (s *DeviceMapping) GetDeviceID() string {
	return s.DeviceID
}

// GetOwnerName returns the value of OwnerName.
func (s *DeviceMapping) GetOwnerName() string {
	return s.OwnerName
}

// GetUserID returns the value of UserID.
func (s *DeviceMapping) GetUserID() string {
	return s.UserID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *DeviceMapping) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *DeviceMapping) SetID(val int32) {
	s.ID = val
}

// SetDeviceID sets the value of DeviceID.
func (s *DeviceMapping) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetOwnerName sets the value of OwnerName.
func (s *DeviceMapping) SetOwnerName(val string) {
	s.OwnerName = val
}

// SetUserID sets the value of UserID.
func (s *DeviceMapping) SetUserID(val string) {
	s.UserID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *DeviceMapping) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/DuplicateGroup
type DuplicateGroup struct {
	Memories []Memory `json:"memories"`
}

// GetMemories returns the value of Memories.
func (s *DuplicateGroup) GetMemories() []Memory {
	return s.Memories
}

// SetMemories sets the value of Memories.
func (s *DuplicateGroup) SetMemories(val []Memory) {
	s.Memories = val
}

type ForgetDeleteOK struct {
	Deleted int32 `json:"deleted"`
}

// GetDeleted returns the value of Deleted.
func (s *ForgetDeleteOK) GetDeleted() int32 {
	return s.Deleted
}

// SetDeleted sets the value of Deleted.
func (s *ForgetDeleteOK) SetDeleted(val int32) {
	s.Deleted = val
}

// Ref: #/components/schemas/ForgetDeleteRequest
type ForgetDeleteRequest struct {
	DeleteIds []string `json:"delete_ids"`
}

// GetDeleteIds returns the value of DeleteIds.
func (s *ForgetDeleteRequest) GetDeleteIds() []string {
	return s.DeleteIds
}

// SetDeleteIds sets the value of DeleteIds.
func (s *ForgetDeleteRequest) SetDeleteIds(val []string) {
	s.DeleteIds = val
}

// Ref: #/components/schemas/ForgetGroup
type ForgetGroup struct {
	Type        string   `json:"type"`
	Members     []Memory `json:"members"`
	AvgDistance float64  `json:"avg_distance"`
}

// GetType returns the value of Type.
func (s *ForgetGroup) GetType() string {
	return s.Type
}

// GetMembers returns the value of Members.
func (s *ForgetGroup) GetMembers() []Memory {
	return s.Members
}

// GetAvgDistance returns the value of AvgDistance.
func (s *ForgetGroup) GetAvgDistance() float64 {
	return s.AvgDistance
}

// SetType sets the value of Type.
func (s *ForgetGroup) SetType(val string) {
	s.Type = val
}

// SetMembers sets the value of Members.
func (s *ForgetGroup) SetMembers(val []Memory) {
	s.Members = val
}

// SetAvgDistance sets the value of AvgDistance.
func (s *ForgetGroup) SetAvgDistance(val float64) {
	s.AvgDistance = val
}

// Paginated list wrapper.
type ForgetGroupsOK struct {
	Data  []ForgetGroup `json:"data"`
	Total int32         `json:"total"`
}

// GetData returns the value of Data.
func (s *ForgetGroupsOK) GetData() []ForgetGroup {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *ForgetGroupsOK) GetTotal() int32 {
	return s.Total
}

// SetData sets the value of Data.
func (s *ForgetGroupsOK) SetData(val []ForgetGroup) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *ForgetGroupsOK) SetTotal(val int32) {
	s.Total = val
}

type ForgetMergeOK struct {
	Deleted int32 `json:"deleted"`
	Merged  bool  `json:"merged"`
}

// GetDeleted returns the value of Deleted.
func (s *ForgetMergeOK) GetDeleted() int32 {
	return s.Deleted
}

// GetMerged returns the value of Merged.
func (s *ForgetMergeOK) GetMerged() bool {
	return s.Merged
}

// SetDeleted sets the value of Deleted.
func (s *ForgetMergeOK) SetDeleted(val int32) {
	s.Deleted = val
}

// SetMerged sets the value of Merged.
func (s *ForgetMergeOK) SetMerged(val bool) {
	s.Merged = val
}

// Ref: #/components/schemas/ForgetMergeRequest
type ForgetMergeRequest struct {
	DeleteIds     []string `json:"delete_ids"`
	MergedContent string   `json:"merged_content"`
	Type          string   `json:"type"`
}

// GetDeleteIds returns the value of DeleteIds.
func (s *ForgetMergeRequest) GetDeleteIds() []string {
	return s.DeleteIds
}

// GetMergedContent returns the value of MergedContent.
func (s *ForgetMergeRequest) GetMergedContent() string {
	return s.MergedContent
}

// GetType returns the value of Type.
func (s *ForgetMergeRequest) GetType() string {
	return s.Type
}

// SetDeleteIds sets the value of DeleteIds.
func (s *ForgetMergeRequest) SetDeleteIds(val []string) {
	s.DeleteIds = val
}

// SetMergedContent sets the value of MergedContent.
func (s *ForgetMergeRequest) SetMergedContent(val string) {
	s.MergedContent = val
}

// SetType sets the value of Type.
func (s *ForgetMergeRequest) SetType(val string) {
	s.Type = val
}

type ForgetRunReq struct {
	SimilarityThreshold OptFloat64 `json:"similarity_threshold"`
}

// GetSimilarityThreshold returns the value of SimilarityThreshold.
func (s *ForgetRunReq) GetSimilarityThreshold() OptFloat64 {
	return s.SimilarityThreshold
}

// SetSimilarityThreshold sets the value of SimilarityThreshold.
func (s *ForgetRunReq) SetSimilarityThreshold(val OptFloat64) {
	s.SimilarityThreshold = val
}

// Ref: #/components/schemas/Guild
type Guild struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	UpdatedAt    string `json:"updated_at"`
	MemberCount  int32  `json:"member_count"`
	ChannelCount int32  `json:"channel_count"`
}

// GetID returns the value of ID.
func (s *Guild) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Guild) GetName() string {
	return s.Name
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Guild) GetUpdatedAt() string {
	return s.UpdatedAt
}

// GetMemberCount returns the value of MemberCount.
func (s *Guild) GetMemberCount() int32 {
	return s.MemberCount
}

// GetChannelCount returns the value of ChannelCount.
func (s *Guild) GetChannelCount() int32 {
	return s.ChannelCount
}

// SetID sets the value of ID.
func (s *Guild) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Guild) SetName(val string) {
	s.Name = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Guild) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

// SetMemberCount sets the value of MemberCount.
func (s *Guild) SetMemberCount(val int32) {
	s.MemberCount = val
}

// SetChannelCount sets the value of ChannelCount.
func (s *Guild) SetChannelCount(val int32) {
	s.ChannelCount = val
}

// Ref: #/components/schemas/GuildChannel
type GuildChannel struct {
	ChannelID         string    `json:"channel_id"`
	ChannelName       string    `json:"channel_name"`
	UserCount         int32     `json:"user_count"`
	LastSeenAt        string    `json:"last_seen_at"`
	LastUserMessageAt OptString `json:"last_user_message_at"`
}

// GetChannelID returns the value of ChannelID.
func (s *GuildChannel) GetChannelID() string {
	return s.ChannelID
}

// GetChannelName returns the value of ChannelName.
func (s *GuildChannel) GetChannelName() string {
	return s.ChannelName
}

// GetUserCount returns the value of UserCount.
func (s *GuildChannel) GetUserCount() int32 {
	return s.UserCount
}

// GetLastSeenAt returns the value of LastSeenAt.
func (s *GuildChannel) GetLastSeenAt() string {
	return s.LastSeenAt
}

// GetLastUserMessageAt returns the value of LastUserMessageAt.
func (s *GuildChannel) GetLastUserMessageAt() OptString {
	return s.LastUserMessageAt
}

// SetChannelID sets the value of ChannelID.
func (s *GuildChannel) SetChannelID(val string) {
	s.ChannelID = val
}

// SetChannelName sets the value of ChannelName.
func (s *GuildChannel) SetChannelName(val string) {
	s.ChannelName = val
}

// SetUserCount sets the value of UserCount.
func (s *GuildChannel) SetUserCount(val int32) {
	s.UserCount = val
}

// SetLastSeenAt sets the value of LastSeenAt.
func (s *GuildChannel) SetLastSeenAt(val string) {
	s.LastSeenAt = val
}

// SetLastUserMessageAt sets the value of LastUserMessageAt.
func (s *GuildChannel) SetLastUserMessageAt(val OptString) {
	s.LastUserMessageAt = val
}

type GuildsChannelsOK struct {
	Data []GuildChannel `json:"data"`
}

// GetData returns the value of Data.
func (s *GuildsChannelsOK) GetData() []GuildChannel {
	return s.Data
}

// SetData sets the value of Data.
func (s *GuildsChannelsOK) SetData(val []GuildChannel) {
	s.Data = val
}

type GuildsListOK struct {
	Data []Guild `json:"data"`
}

// GetData returns the value of Data.
func (s *GuildsListOK) GetData() []Guild {
	return s.Data
}

// SetData sets the value of Data.
func (s *GuildsListOK) SetData(val []Guild) {
	s.Data = val
}

type HealthCheckOK struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthCheckOK) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthCheckOK) SetStatus(val string) {
	s.Status = val
}

// LocationDeleteDeviceNoContent is response for LocationDeleteDevice operation.
type LocationDeleteDeviceNoContent struct{}

// LocationDeletePlaceNoContent is response for LocationDeletePlace operation.
type LocationDeletePlaceNoContent struct{}

type LocationListDevicesOK struct {
	Data []DeviceMapping `json:"data"`
}

// GetData returns the value of Data.
func (s *LocationListDevicesOK) GetData() []DeviceMapping {
	return s.Data
}

// SetData sets the value of Data.
func (s *LocationListDevicesOK) SetData(val []DeviceMapping) {
	s.Data = val
}

type LocationListPlacesOK struct {
	Data []Place `json:"data"`
}

// GetData returns the value of Data.
func (s *LocationListPlacesOK) GetData() []Place {
	return s.Data
}

// SetData sets the value of Data.
func (s *LocationListPlacesOK) SetData(val []Place) {
	s.Data = val
}

type LocationUserLocationOK struct {
	Data []UserLocation `json:"data"`
}

// GetData returns the value of Data.
func (s *LocationUserLocationOK) GetData() []UserLocation {
	return s.Data
}

// SetData sets the value of Data.
func (s *LocationUserLocationOK) SetData(val []UserLocation) {
	s.Data = val
}

type MemoriesCreateCreated struct {
	Data Memory `json:"data"`
}

// GetData returns the value of Data.
func (s *MemoriesCreateCreated) GetData() Memory {
	return s.Data
}

// SetData sets the value of Data.
func (s *MemoriesCreateCreated) SetData(val Memory) {
	s.Data = val
}

// MemoriesDeleteNoContent is response for MemoriesDelete operation.
type MemoriesDeleteNoContent struct{}

// Paginated list wrapper.
type MemoriesDuplicatesOK struct {
	Data  []DuplicateGroup `json:"data"`
	Total int32            `json:"total"`
}

// GetData returns the value of Data.
func (s *MemoriesDuplicatesOK) GetData() []DuplicateGroup {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *MemoriesDuplicatesOK) GetTotal() int32 {
	return s.Total
}

// SetData sets the value of Data.
func (s *MemoriesDuplicatesOK) SetData(val []DuplicateGroup) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *MemoriesDuplicatesOK) SetTotal(val int32) {
	s.Total = val
}

type MemoriesGetOK struct {
	Data Memory `json:"data"`
}

// GetData returns the value of Data.
func (s *MemoriesGetOK) GetData() Memory {
	return s.Data
}

// SetData sets the value of Data.
func (s *MemoriesGetOK) SetData(val Memory) {
	s.Data = val
}

// Paginated list wrapper.
type MemoriesListOK struct {
	Data  []Memory `json:"data"`
	Total int32    `json:"total"`
}

// GetData returns the value of Data.
func (s *MemoriesListOK) GetData() []Memory {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *MemoriesListOK) GetTotal() int32 {
	return s.Total
}

// SetData sets the value of Data.
func (s *MemoriesListOK) SetData(val []Memory) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *MemoriesListOK) SetTotal(val int32) {
	s.Total = val
}

// Paginated list wrapper.
type MemoriesListWithVecOK struct {
	Data  []Memory `json:"data"`
	Total int32    `json:"total"`
}

// GetData returns the value of Data.
func (s *MemoriesListWithVecOK) GetData() []Memory {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *MemoriesListWithVecOK) GetTotal() int32 {
	return s.Total
}

// SetData sets the value of Data.
func (s *MemoriesListWithVecOK) SetData(val []Memory) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *MemoriesListWithVecOK) SetTotal(val int32) {
	s.Total = val
}

type MemoriesUpdateOK struct {
	Data Memory `json:"data"`
}

// GetData returns the value of Data.
func (s *MemoriesUpdateOK) GetData() Memory {
	return s.Data
}

// SetData sets the value of Data.
func (s *MemoriesUpdateOK) SetData(val Memory) {
	s.Data = val
}

// Ref: #/components/schemas/Memory
type Memory struct {
	ID        string            `json:"id"`
	Type      string            `json:"type"`
	Content   string            `json:"content"`
	Metadata  OptMemoryMetadata `json:"metadata"`
	CreatedAt string            `json:"created_at"`
	UpdatedAt string            `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Memory) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *Memory) GetType() string {
	return s.Type
}

// GetContent returns the value of Content.
func (s *Memory) GetContent() string {
	return s.Content
}

// GetMetadata returns the value of Metadata.
func (s *Memory) GetMetadata() OptMemoryMetadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Memory) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Memory) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Memory) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *Memory) SetType(val string) {
	s.Type = val
}

// SetContent sets the value of Content.
func (s *Memory) SetContent(val string) {
	s.Content = val
}

// SetMetadata sets the value of Metadata.
func (s *Memory) SetMetadata(val OptMemoryMetadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Memory) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Memory) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

type MemoryMetadata map[string]jx.Raw

func (s *MemoryMetadata) init() MemoryMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/OkResponse
type OkResponse struct {
	Ok bool `json:"ok"`
}

// GetOk returns the value of Ok.
func (s *OkResponse) GetOk() bool {
	return s.Ok
}

// SetOk sets the value of Ok.
func (s *OkResponse) SetOk(val bool) {
	s.Ok = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptContextGetSource returns new OptContextGetSource with value set to v.
func NewOptContextGetSource(v ContextGetSource) OptContextGetSource {
	return OptContextGetSource{
		Value: v,
		Set:   true,
	}
}

// OptContextGetSource is optional ContextGetSource.
type OptContextGetSource struct {
	Value ContextGetSource
	Set   bool
}

// IsSet returns true if OptContextGetSource was set.
func (o OptContextGetSource) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptContextGetSource) Reset() {
	var v ContextGetSource
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptContextGetSource) SetTo(v ContextGetSource) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptContextGetSource) Get() (v ContextGetSource, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptContextGetSource) Or(d ContextGetSource) ContextGetSource {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateActionRequestMode returns new OptCreateActionRequestMode with value set to v.
func NewOptCreateActionRequestMode(v CreateActionRequestMode) OptCreateActionRequestMode {
	return OptCreateActionRequestMode{
		Value: v,
		Set:   true,
	}
}

// OptCreateActionRequestMode is optional CreateActionRequestMode.
type OptCreateActionRequestMode struct {
	Value CreateActionRequestMode
	Set   bool
}

// IsSet returns true if OptCreateActionRequestMode was set.
func (o OptCreateActionRequestMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateActionRequestMode) Reset() {
	var v CreateActionRequestMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateActionRequestMode) SetTo(v CreateActionRequestMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateActionRequestMode) Get() (v CreateActionRequestMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateActionRequestMode) Or(d CreateActionRequestMode) CreateActionRequestMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateMemoryRequestMetadata returns new OptCreateMemoryRequestMetadata with value set to v.
func NewOptCreateMemoryRequestMetadata(v CreateMemoryRequestMetadata) OptCreateMemoryRequestMetadata {
	return OptCreateMemoryRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptCreateMemoryRequestMetadata is optional CreateMemoryRequestMetadata.
type OptCreateMemoryRequestMetadata struct {
	Value CreateMemoryRequestMetadata
	Set   bool
}

// IsSet returns true if OptCreateMemoryRequestMetadata was set.
func (o OptCreateMemoryRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateMemoryRequestMetadata) Reset() {
	var v CreateMemoryRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateMemoryRequestMetadata) SetTo(v CreateMemoryRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateMemoryRequestMetadata) Get() (v CreateMemoryRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateMemoryRequestMetadata) Or(d CreateMemoryRequestMetadata) CreateMemoryRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptForgetRunReq returns new OptForgetRunReq with value set to v.
func NewOptForgetRunReq(v ForgetRunReq) OptForgetRunReq {
	return OptForgetRunReq{
		Value: v,
		Set:   true,
	}
}

// OptForgetRunReq is optional ForgetRunReq.
type OptForgetRunReq struct {
	Value ForgetRunReq
	Set   bool
}

// IsSet returns true if OptForgetRunReq was set.
func (o OptForgetRunReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptForgetRunReq) Reset() {
	var v ForgetRunReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptForgetRunReq) SetTo(v ForgetRunReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptForgetRunReq) Get() (v ForgetRunReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptForgetRunReq) Or(d ForgetRunReq) ForgetRunReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMemoryMetadata returns new OptMemoryMetadata with value set to v.
func NewOptMemoryMetadata(v MemoryMetadata) OptMemoryMetadata {
	return OptMemoryMetadata{
		Value: v,
		Set:   true,
	}
}

// OptMemoryMetadata is optional MemoryMetadata.
type OptMemoryMetadata struct {
	Value MemoryMetadata
	Set   bool
}

// IsSet returns true if OptMemoryMetadata was set.
func (o OptMemoryMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMemoryMetadata) Reset() {
	var v MemoryMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMemoryMetadata) SetTo(v MemoryMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMemoryMetadata) Get() (v MemoryMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMemoryMetadata) Or(d MemoryMetadata) MemoryMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateActionRequestMode returns new OptUpdateActionRequestMode with value set to v.
func NewOptUpdateActionRequestMode(v UpdateActionRequestMode) OptUpdateActionRequestMode {
	return OptUpdateActionRequestMode{
		Value: v,
		Set:   true,
	}
}

// OptUpdateActionRequestMode is optional UpdateActionRequestMode.
type OptUpdateActionRequestMode struct {
	Value UpdateActionRequestMode
	Set   bool
}

// IsSet returns true if OptUpdateActionRequestMode was set.
func (o OptUpdateActionRequestMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateActionRequestMode) Reset() {
	var v UpdateActionRequestMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateActionRequestMode) SetTo(v UpdateActionRequestMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateActionRequestMode) Get() (v UpdateActionRequestMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateActionRequestMode) Or(d UpdateActionRequestMode) UpdateActionRequestMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateChannelSettingRequestMode returns new OptUpdateChannelSettingRequestMode with value set to v.
func NewOptUpdateChannelSettingRequestMode(v UpdateChannelSettingRequestMode) OptUpdateChannelSettingRequestMode {
	return OptUpdateChannelSettingRequestMode{
		Value: v,
		Set:   true,
	}
}

// OptUpdateChannelSettingRequestMode is optional UpdateChannelSettingRequestMode.
type OptUpdateChannelSettingRequestMode struct {
	Value UpdateChannelSettingRequestMode
	Set   bool
}

// IsSet returns true if OptUpdateChannelSettingRequestMode was set.
func (o OptUpdateChannelSettingRequestMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateChannelSettingRequestMode) Reset() {
	var v UpdateChannelSettingRequestMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateChannelSettingRequestMode) SetTo(v UpdateChannelSettingRequestMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateChannelSettingRequestMode) Get() (v UpdateChannelSettingRequestMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateChannelSettingRequestMode) Or(d UpdateChannelSettingRequestMode) UpdateChannelSettingRequestMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateMemoryRequestMetadata returns new OptUpdateMemoryRequestMetadata with value set to v.
func NewOptUpdateMemoryRequestMetadata(v UpdateMemoryRequestMetadata) OptUpdateMemoryRequestMetadata {
	return OptUpdateMemoryRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptUpdateMemoryRequestMetadata is optional UpdateMemoryRequestMetadata.
type OptUpdateMemoryRequestMetadata struct {
	Value UpdateMemoryRequestMetadata
	Set   bool
}

// IsSet returns true if OptUpdateMemoryRequestMetadata was set.
func (o OptUpdateMemoryRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateMemoryRequestMetadata) Reset() {
	var v UpdateMemoryRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateMemoryRequestMetadata) SetTo(v UpdateMemoryRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateMemoryRequestMetadata) Get() (v UpdateMemoryRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateMemoryRequestMetadata) Or(d UpdateMemoryRequestMetadata) UpdateMemoryRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateUserRequestRole returns new OptUpdateUserRequestRole with value set to v.
func NewOptUpdateUserRequestRole(v UpdateUserRequestRole) OptUpdateUserRequestRole {
	return OptUpdateUserRequestRole{
		Value: v,
		Set:   true,
	}
}

// OptUpdateUserRequestRole is optional UpdateUserRequestRole.
type OptUpdateUserRequestRole struct {
	Value UpdateUserRequestRole
	Set   bool
}

// IsSet returns true if OptUpdateUserRequestRole was set.
func (o OptUpdateUserRequestRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateUserRequestRole) Reset() {
	var v UpdateUserRequestRole
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateUserRequestRole) SetTo(v UpdateUserRequestRole) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateUserRequestRole) Get() (v UpdateUserRequestRole, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateUserRequestRole) Or(d UpdateUserRequestRole) UpdateUserRequestRole {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserMetadata returns new OptUserMetadata with value set to v.
func NewOptUserMetadata(v UserMetadata) OptUserMetadata {
	return OptUserMetadata{
		Value: v,
		Set:   true,
	}
}

// OptUserMetadata is optional UserMetadata.
type OptUserMetadata struct {
	Value UserMetadata
	Set   bool
}

// IsSet returns true if OptUserMetadata was set.
func (o OptUserMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserMetadata) Reset() {
	var v UserMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserMetadata) SetTo(v UserMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserMetadata) Get() (v UserMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserMetadata) Or(d UserMetadata) UserMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Place
type Place struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	RadiusM   float64 `json:"radius_m"`
	CreatedAt string  `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Place) GetID() int32 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Place) GetName() string {
	return s.Name
}

// GetLatitude returns the value of Latitude.
func (s *Place) GetLatitude() float64 {
	return s.Latitude
}

// GetLongitude returns the value of Longitude.
func (s *Place) GetLongitude() float64 {
	return s.Longitude
}

// GetRadiusM returns the value of RadiusM.
func (s *Place) GetRadiusM() float64 {
	return s.RadiusM
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Place) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Place) SetID(val int32) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Place) SetName(val string) {
	s.Name = val
}

// SetLatitude sets the value of Latitude.
func (s *Place) SetLatitude(val float64) {
	s.Latitude = val
}

// SetLongitude sets the value of Longitude.
func (s *Place) SetLongitude(val float64) {
	s.Longitude = val
}

// SetRadiusM sets the value of RadiusM.
func (s *Place) SetRadiusM(val float64) {
	s.RadiusM = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Place) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/Platform
type Platform struct {
	Platform       string `json:"platform"`
	PlatformUserID string `json:"platform_user_id"`
	PlatformName   string `json:"platform_name"`
}

// GetPlatform returns the value of Platform.
func (s *Platform) GetPlatform() string {
	return s.Platform
}

// GetPlatformUserID returns the value of PlatformUserID.
func (s *Platform) GetPlatformUserID() string {
	return s.PlatformUserID
}

// GetPlatformName returns the value of PlatformName.
func (s *Platform) GetPlatformName() string {
	return s.PlatformName
}

// SetPlatform sets the value of Platform.
func (s *Platform) SetPlatform(val string) {
	s.Platform = val
}

// SetPlatformUserID sets the value of PlatformUserID.
func (s *Platform) SetPlatformUserID(val string) {
	s.PlatformUserID = val
}

// SetPlatformName sets the value of PlatformName.
func (s *Platform) SetPlatformName(val string) {
	s.PlatformName = val
}

// Ref: #/components/schemas/PromptFile
type PromptFile struct {
	Name      string `json:"name"`
	Content   string `json:"content"`
	UpdatedAt string `json:"updated_at"`
}

// GetName returns the value of Name.
func (s *PromptFile) GetName() string {
	return s.Name
}

// GetContent returns the value of Content.
func (s *PromptFile) GetContent() string {
	return s.Content
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *PromptFile) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetName sets the value of Name.
func (s *PromptFile) SetName(val string) {
	s.Name = val
}

// SetContent sets the value of Content.
func (s *PromptFile) SetContent(val string) {
	s.Content = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *PromptFile) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

type PromptsUpdateOK struct {
	Ok       bool `json:"ok"`
	Reloaded bool `json:"reloaded"`
}

// GetOk returns the value of Ok.
func (s *PromptsUpdateOK) GetOk() bool {
	return s.Ok
}

// GetReloaded returns the value of Reloaded.
func (s *PromptsUpdateOK) GetReloaded() bool {
	return s.Reloaded
}

// SetOk sets the value of Ok.
func (s *PromptsUpdateOK) SetOk(val bool) {
	s.Ok = val
}

// SetReloaded sets the value of Reloaded.
func (s *PromptsUpdateOK) SetReloaded(val bool) {
	s.Reloaded = val
}

// Ref: #/components/schemas/ScheduledAction
type ScheduledAction struct {
	ID            string                `json:"id"`
	ChannelID     string                `json:"channel_id"`
	Content       string                `json:"content"`
	Mode          ScheduledActionMode   `json:"mode"`
	ScheduledAt   string                `json:"scheduled_at"`
	CronExpr      OptString             `json:"cron_expr"`
	RandomMinutes int32                 `json:"random_minutes"`
	CreatedBy     OptString             `json:"created_by"`
	Status        ScheduledActionStatus `json:"status"`
	RetryCount    int32                 `json:"retry_count"`
	ExecutedAt    OptString             `json:"executed_at"`
	CreatedAt     string                `json:"created_at"`
}

// GetID returns the value of ID.
func (s *ScheduledAction) GetID() string {
	return s.ID
}

// GetChannelID returns the value of ChannelID.
func (s *ScheduledAction) GetChannelID() string {
	return s.ChannelID
}

// GetContent returns the value of Content.
func (s *ScheduledAction) GetContent() string {
	return s.Content
}

// GetMode returns the value of Mode.
func (s *ScheduledAction) GetMode() ScheduledActionMode {
	return s.Mode
}

// GetScheduledAt returns the value of ScheduledAt.
func (s *ScheduledAction) GetScheduledAt() string {
	return s.ScheduledAt
}

// GetCronExpr returns the value of CronExpr.
func (s *ScheduledAction) GetCronExpr() OptString {
	return s.CronExpr
}

// GetRandomMinutes returns the value of RandomMinutes.
func (s *ScheduledAction) GetRandomMinutes() int32 {
	return s.RandomMinutes
}

// GetCreatedBy returns the value of CreatedBy.
func (s *ScheduledAction) GetCreatedBy() OptString {
	return s.CreatedBy
}

// GetStatus returns the value of Status.
func (s *ScheduledAction) GetStatus() ScheduledActionStatus {
	return s.Status
}

// GetRetryCount returns the value of RetryCount.
func (s *ScheduledAction) GetRetryCount() int32 {
	return s.RetryCount
}

// GetExecutedAt returns the value of ExecutedAt.
func (s *ScheduledAction) GetExecutedAt() OptString {
	return s.ExecutedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ScheduledAction) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *ScheduledAction) SetID(val string) {
	s.ID = val
}

// SetChannelID sets the value of ChannelID.
func (s *ScheduledAction) SetChannelID(val string) {
	s.ChannelID = val
}

// SetContent sets the value of Content.
func (s *ScheduledAction) SetContent(val string) {
	s.Content = val
}

// SetMode sets the value of Mode.
func (s *ScheduledAction) SetMode(val ScheduledActionMode) {
	s.Mode = val
}

// SetScheduledAt sets the value of ScheduledAt.
func (s *ScheduledAction) SetScheduledAt(val string) {
	s.ScheduledAt = val
}

// SetCronExpr sets the value of CronExpr.
func (s *ScheduledAction) SetCronExpr(val OptString) {
	s.CronExpr = val
}

// SetRandomMinutes sets the value of RandomMinutes.
func (s *ScheduledAction) SetRandomMinutes(val int32) {
	s.RandomMinutes = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *ScheduledAction) SetCreatedBy(val OptString) {
	s.CreatedBy = val
}

// SetStatus sets the value of Status.
func (s *ScheduledAction) SetStatus(val ScheduledActionStatus) {
	s.Status = val
}

// SetRetryCount sets the value of RetryCount.
func (s *ScheduledAction) SetRetryCount(val int32) {
	s.RetryCount = val
}

// SetExecutedAt sets the value of ExecutedAt.
func (s *ScheduledAction) SetExecutedAt(val OptString) {
	s.ExecutedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ScheduledAction) SetCreatedAt(val string) {
	s.CreatedAt = val
}

type ScheduledActionMode string

const (
	ScheduledActionModeDirect ScheduledActionMode = "direct"
	ScheduledActionModePrompt ScheduledActionMode = "prompt"
)

// AllValues returns all ScheduledActionMode values.
func (ScheduledActionMode) AllValues() []ScheduledActionMode {
	return []ScheduledActionMode{
		ScheduledActionModeDirect,
		ScheduledActionModePrompt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScheduledActionMode) MarshalText() ([]byte, error) {
	switch s {
	case ScheduledActionModeDirect:
		return []byte(s), nil
	case ScheduledActionModePrompt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScheduledActionMode) UnmarshalText(data []byte) error {
	switch ScheduledActionMode(data) {
	case ScheduledActionModeDirect:
		*s = ScheduledActionModeDirect
		return nil
	case ScheduledActionModePrompt:
		*s = ScheduledActionModePrompt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ScheduledActionStatus string

const (
	ScheduledActionStatusPending   ScheduledActionStatus = "pending"
	ScheduledActionStatusExecuted  ScheduledActionStatus = "executed"
	ScheduledActionStatusCancelled ScheduledActionStatus = "cancelled"
	ScheduledActionStatusFailed    ScheduledActionStatus = "failed"
)

// AllValues returns all ScheduledActionStatus values.
func (ScheduledActionStatus) AllValues() []ScheduledActionStatus {
	return []ScheduledActionStatus{
		ScheduledActionStatusPending,
		ScheduledActionStatusExecuted,
		ScheduledActionStatusCancelled,
		ScheduledActionStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScheduledActionStatus) MarshalText() ([]byte, error) {
	switch s {
	case ScheduledActionStatusPending:
		return []byte(s), nil
	case ScheduledActionStatusExecuted:
		return []byte(s), nil
	case ScheduledActionStatusCancelled:
		return []byte(s), nil
	case ScheduledActionStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScheduledActionStatus) UnmarshalText(data []byte) error {
	switch ScheduledActionStatus(data) {
	case ScheduledActionStatusPending:
		*s = ScheduledActionStatusPending
		return nil
	case ScheduledActionStatusExecuted:
		*s = ScheduledActionStatusExecuted
		return nil
	case ScheduledActionStatusCancelled:
		*s = ScheduledActionStatusCancelled
		return nil
	case ScheduledActionStatusFailed:
		*s = ScheduledActionStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ScheduledActionsCreateCreated struct {
	Data ScheduledActionsCreateCreatedData `json:"data"`
}

// GetData returns the value of Data.
func (s *ScheduledActionsCreateCreated) GetData() ScheduledActionsCreateCreatedData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ScheduledActionsCreateCreated) SetData(val ScheduledActionsCreateCreatedData) {
	s.Data = val
}

type ScheduledActionsCreateCreatedData struct {
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *ScheduledActionsCreateCreatedData) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *ScheduledActionsCreateCreatedData) SetID(val string) {
	s.ID = val
}

type ScheduledActionsListOK struct {
	Data []ScheduledAction `json:"data"`
}

// GetData returns the value of Data.
func (s *ScheduledActionsListOK) GetData() []ScheduledAction {
	return s.Data
}

// SetData sets the value of Data.
func (s *ScheduledActionsListOK) SetData(val []ScheduledAction) {
	s.Data = val
}

// Ref: #/components/schemas/UpdateActionRequest
type UpdateActionRequest struct {
	ChannelID   OptString                  `json:"channel_id"`
	Content     OptString                  `json:"content"`
	Mode        OptUpdateActionRequestMode `json:"mode"`
	ScheduledAt OptString                  `json:"scheduled_at"`
	CronExpr    OptString                  `json:"cron_expr"`
	Status      OptString                  `json:"status"`
}

// GetChannelID returns the value of ChannelID.
func (s *UpdateActionRequest) GetChannelID() OptString {
	return s.ChannelID
}

// GetContent returns the value of Content.
func (s *UpdateActionRequest) GetContent() OptString {
	return s.Content
}

// GetMode returns the value of Mode.
func (s *UpdateActionRequest) GetMode() OptUpdateActionRequestMode {
	return s.Mode
}

// GetScheduledAt returns the value of ScheduledAt.
func (s *UpdateActionRequest) GetScheduledAt() OptString {
	return s.ScheduledAt
}

// GetCronExpr returns the value of CronExpr.
func (s *UpdateActionRequest) GetCronExpr() OptString {
	return s.CronExpr
}

// GetStatus returns the value of Status.
func (s *UpdateActionRequest) GetStatus() OptString {
	return s.Status
}

// SetChannelID sets the value of ChannelID.
func (s *UpdateActionRequest) SetChannelID(val OptString) {
	s.ChannelID = val
}

// SetContent sets the value of Content.
func (s *UpdateActionRequest) SetContent(val OptString) {
	s.Content = val
}

// SetMode sets the value of Mode.
func (s *UpdateActionRequest) SetMode(val OptUpdateActionRequestMode) {
	s.Mode = val
}

// SetScheduledAt sets the value of ScheduledAt.
func (s *UpdateActionRequest) SetScheduledAt(val OptString) {
	s.ScheduledAt = val
}

// SetCronExpr sets the value of CronExpr.
func (s *UpdateActionRequest) SetCronExpr(val OptString) {
	s.CronExpr = val
}

// SetStatus sets the value of Status.
func (s *UpdateActionRequest) SetStatus(val OptString) {
	s.Status = val
}

type UpdateActionRequestMode string

const (
	UpdateActionRequestModeDirect UpdateActionRequestMode = "direct"
	UpdateActionRequestModePrompt UpdateActionRequestMode = "prompt"
)

// AllValues returns all UpdateActionRequestMode values.
func (UpdateActionRequestMode) AllValues() []UpdateActionRequestMode {
	return []UpdateActionRequestMode{
		UpdateActionRequestModeDirect,
		UpdateActionRequestModePrompt,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateActionRequestMode) MarshalText() ([]byte, error) {
	switch s {
	case UpdateActionRequestModeDirect:
		return []byte(s), nil
	case UpdateActionRequestModePrompt:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateActionRequestMode) UnmarshalText(data []byte) error {
	switch UpdateActionRequestMode(data) {
	case UpdateActionRequestModeDirect:
		*s = UpdateActionRequestModeDirect
		return nil
	case UpdateActionRequestModePrompt:
		*s = UpdateActionRequestModePrompt
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/UpdateChannelSettingRequest
type UpdateChannelSettingRequest struct {
	Mode    OptUpdateChannelSettingRequestMode `json:"mode"`
	Home    OptBool                            `json:"home"`
	GuildID OptString                          `json:"guild_id"`
}

// GetMode returns the value of Mode.
func (s *UpdateChannelSettingRequest) GetMode() OptUpdateChannelSettingRequestMode {
	return s.Mode
}

// GetHome returns the value of Home.
func (s *UpdateChannelSettingRequest) GetHome() OptBool {
	return s.Home
}

// GetGuildID returns the value of GuildID.
func (s *UpdateChannelSettingRequest) GetGuildID() OptString {
	return s.GuildID
}

// SetMode sets the value of Mode.
func (s *UpdateChannelSettingRequest) SetMode(val OptUpdateChannelSettingRequestMode) {
	s.Mode = val
}

// SetHome sets the value of Home.
func (s *UpdateChannelSettingRequest) SetHome(val OptBool) {
	s.Home = val
}

// SetGuildID sets the value of GuildID.
func (s *UpdateChannelSettingRequest) SetGuildID(val OptString) {
	s.GuildID = val
}

type UpdateChannelSettingRequestMode string

const (
	UpdateChannelSettingRequestModeActive   UpdateChannelSettingRequestMode = "active"
	UpdateChannelSettingRequestModeListen   UpdateChannelSettingRequestMode = "listen"
	UpdateChannelSettingRequestModeDisabled UpdateChannelSettingRequestMode = "disabled"
)

// AllValues returns all UpdateChannelSettingRequestMode values.
func (UpdateChannelSettingRequestMode) AllValues() []UpdateChannelSettingRequestMode {
	return []UpdateChannelSettingRequestMode{
		UpdateChannelSettingRequestModeActive,
		UpdateChannelSettingRequestModeListen,
		UpdateChannelSettingRequestModeDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateChannelSettingRequestMode) MarshalText() ([]byte, error) {
	switch s {
	case UpdateChannelSettingRequestModeActive:
		return []byte(s), nil
	case UpdateChannelSettingRequestModeListen:
		return []byte(s), nil
	case UpdateChannelSettingRequestModeDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateChannelSettingRequestMode) UnmarshalText(data []byte) error {
	switch UpdateChannelSettingRequestMode(data) {
	case UpdateChannelSettingRequestModeActive:
		*s = UpdateChannelSettingRequestModeActive
		return nil
	case UpdateChannelSettingRequestModeListen:
		*s = UpdateChannelSettingRequestModeListen
		return nil
	case UpdateChannelSettingRequestModeDisabled:
		*s = UpdateChannelSettingRequestModeDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/UpdateDeviceRequest
type UpdateDeviceRequest struct {
	OwnerName OptString `json:"owner_name"`
	UserID    OptString `json:"user_id"`
}

// GetOwnerName returns the value of OwnerName.
func (s *UpdateDeviceRequest) GetOwnerName() OptString {
	return s.OwnerName
}

// GetUserID returns the value of UserID.
func (s *UpdateDeviceRequest) GetUserID() OptString {
	return s.UserID
}

// SetOwnerName sets the value of OwnerName.
func (s *UpdateDeviceRequest) SetOwnerName(val OptString) {
	s.OwnerName = val
}

// SetUserID sets the value of UserID.
func (s *UpdateDeviceRequest) SetUserID(val OptString) {
	s.UserID = val
}

// Ref: #/components/schemas/UpdateMemoryRequest
type UpdateMemoryRequest struct {
	Type     OptString                      `json:"type"`
	Content  OptString                      `json:"content"`
	Metadata OptUpdateMemoryRequestMetadata `json:"metadata"`
}

// GetType returns the value of Type.
func (s *UpdateMemoryRequest) GetType() OptString {
	return s.Type
}

// GetContent returns the value of Content.
func (s *UpdateMemoryRequest) GetContent() OptString {
	return s.Content
}

// GetMetadata returns the value of Metadata.
func (s *UpdateMemoryRequest) GetMetadata() OptUpdateMemoryRequestMetadata {
	return s.Metadata
}

// SetType sets the value of Type.
func (s *UpdateMemoryRequest) SetType(val OptString) {
	s.Type = val
}

// SetContent sets the value of Content.
func (s *UpdateMemoryRequest) SetContent(val OptString) {
	s.Content = val
}

// SetMetadata sets the value of Metadata.
func (s *UpdateMemoryRequest) SetMetadata(val OptUpdateMemoryRequestMetadata) {
	s.Metadata = val
}

type UpdateMemoryRequestMetadata map[string]jx.Raw

func (s *UpdateMemoryRequestMetadata) init() UpdateMemoryRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/UpdatePlaceRequest
type UpdatePlaceRequest struct {
	Name      OptString  `json:"name"`
	Latitude  OptFloat64 `json:"latitude"`
	Longitude OptFloat64 `json:"longitude"`
	RadiusM   OptFloat64 `json:"radius_m"`
}

// GetName returns the value of Name.
func (s *UpdatePlaceRequest) GetName() OptString {
	return s.Name
}

// GetLatitude returns the value of Latitude.
func (s *UpdatePlaceRequest) GetLatitude() OptFloat64 {
	return s.Latitude
}

// GetLongitude returns the value of Longitude.
func (s *UpdatePlaceRequest) GetLongitude() OptFloat64 {
	return s.Longitude
}

// GetRadiusM returns the value of RadiusM.
func (s *UpdatePlaceRequest) GetRadiusM() OptFloat64 {
	return s.RadiusM
}

// SetName sets the value of Name.
func (s *UpdatePlaceRequest) SetName(val OptString) {
	s.Name = val
}

// SetLatitude sets the value of Latitude.
func (s *UpdatePlaceRequest) SetLatitude(val OptFloat64) {
	s.Latitude = val
}

// SetLongitude sets the value of Longitude.
func (s *UpdatePlaceRequest) SetLongitude(val OptFloat64) {
	s.Longitude = val
}

// SetRadiusM sets the value of RadiusM.
func (s *UpdatePlaceRequest) SetRadiusM(val OptFloat64) {
	s.RadiusM = val
}

// Ref: #/components/schemas/UpdatePromptRequest
type UpdatePromptRequest struct {
	Content string `json:"content"`
}

// GetContent returns the value of Content.
func (s *UpdatePromptRequest) GetContent() string {
	return s.Content
}

// SetContent sets the value of Content.
func (s *UpdatePromptRequest) SetContent(val string) {
	s.Content = val
}

// Ref: #/components/schemas/UpdateUserRequest
type UpdateUserRequest struct {
	DisplayName OptString                `json:"display_name"`
	Role        OptUpdateUserRequestRole `json:"role"`
	IsBot       OptBool                  `json:"is_bot"`
}

// GetDisplayName returns the value of DisplayName.
func (s *UpdateUserRequest) GetDisplayName() OptString {
	return s.DisplayName
}

// GetRole returns the value of Role.
func (s *UpdateUserRequest) GetRole() OptUpdateUserRequestRole {
	return s.Role
}

// GetIsBot returns the value of IsBot.
func (s *UpdateUserRequest) GetIsBot() OptBool {
	return s.IsBot
}

// SetDisplayName sets the value of DisplayName.
func (s *UpdateUserRequest) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetRole sets the value of Role.
func (s *UpdateUserRequest) SetRole(val OptUpdateUserRequestRole) {
	s.Role = val
}

// SetIsBot sets the value of IsBot.
func (s *UpdateUserRequest) SetIsBot(val OptBool) {
	s.IsBot = val
}

type UpdateUserRequestRole string

const (
	UpdateUserRequestRoleOwner  UpdateUserRequestRole = "owner"
	UpdateUserRequestRoleMember UpdateUserRequestRole = "member"
	UpdateUserRequestRoleGuest  UpdateUserRequestRole = "guest"
)

// AllValues returns all UpdateUserRequestRole values.
func (UpdateUserRequestRole) AllValues() []UpdateUserRequestRole {
	return []UpdateUserRequestRole{
		UpdateUserRequestRoleOwner,
		UpdateUserRequestRoleMember,
		UpdateUserRequestRoleGuest,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateUserRequestRole) MarshalText() ([]byte, error) {
	switch s {
	case UpdateUserRequestRoleOwner:
		return []byte(s), nil
	case UpdateUserRequestRoleMember:
		return []byte(s), nil
	case UpdateUserRequestRoleGuest:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateUserRequestRole) UnmarshalText(data []byte) error {
	switch UpdateUserRequestRole(data) {
	case UpdateUserRequestRoleOwner:
		*s = UpdateUserRequestRoleOwner
		return nil
	case UpdateUserRequestRoleMember:
		*s = UpdateUserRequestRoleMember
		return nil
	case UpdateUserRequestRoleGuest:
		*s = UpdateUserRequestRoleGuest
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/User
type User struct {
	ID          string          `json:"id"`
	DisplayName string          `json:"display_name"`
	Role        UserRole        `json:"role"`
	IsBot       bool            `json:"is_bot"`
	Metadata    OptUserMetadata `json:"metadata"`
	CreatedAt   string          `json:"created_at"`
	UpdatedAt   string          `json:"updated_at"`
	Platforms   []Platform      `json:"platforms"`
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *User) GetDisplayName() string {
	return s.DisplayName
}

// GetRole returns the value of Role.
func (s *User) GetRole() UserRole {
	return s.Role
}

// GetIsBot returns the value of IsBot.
func (s *User) GetIsBot() bool {
	return s.IsBot
}

// GetMetadata returns the value of Metadata.
func (s *User) GetMetadata() OptUserMetadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *User) GetUpdatedAt() string {
	return s.UpdatedAt
}

// GetPlatforms returns the value of Platforms.
func (s *User) GetPlatforms() []Platform {
	return s.Platforms
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *User) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val UserRole) {
	s.Role = val
}

// SetIsBot sets the value of IsBot.
func (s *User) SetIsBot(val bool) {
	s.IsBot = val
}

// SetMetadata sets the value of Metadata.
func (s *User) SetMetadata(val OptUserMetadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *User) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

// SetPlatforms sets the value of Platforms.
func (s *User) SetPlatforms(val []Platform) {
	s.Platforms = val
}

// Ref: #/components/schemas/UserGuild
type UserGuild struct {
	GuildID     string `json:"guild_id"`
	GuildName   string `json:"guild_name"`
	ChannelID   string `json:"channel_id"`
	ChannelName string `json:"channel_name"`
	LastSeenAt  string `json:"last_seen_at"`
}

// GetGuildID returns the value of GuildID.
func (s *UserGuild) GetGuildID() string {
	return s.GuildID
}

// GetGuildName returns the value of GuildName.
func (s *UserGuild) GetGuildName() string {
	return s.GuildName
}

// GetChannelID returns the value of ChannelID.
func (s *UserGuild) GetChannelID() string {
	return s.ChannelID
}

// GetChannelName returns the value of ChannelName.
func (s *UserGuild) GetChannelName() string {
	return s.ChannelName
}

// GetLastSeenAt returns the value of LastSeenAt.
func (s *UserGuild) GetLastSeenAt() string {
	return s.LastSeenAt
}

// SetGuildID sets the value of GuildID.
func (s *UserGuild) SetGuildID(val string) {
	s.GuildID = val
}

// SetGuildName sets the value of GuildName.
func (s *UserGuild) SetGuildName(val string) {
	s.GuildName = val
}

// SetChannelID sets the value of ChannelID.
func (s *UserGuild) SetChannelID(val string) {
	s.ChannelID = val
}

// SetChannelName sets the value of ChannelName.
func (s *UserGuild) SetChannelName(val string) {
	s.ChannelName = val
}

// SetLastSeenAt sets the value of LastSeenAt.
func (s *UserGuild) SetLastSeenAt(val string) {
	s.LastSeenAt = val
}

// Ref: #/components/schemas/UserLocation
type UserLocation struct {
	UserID    string     `json:"user_id"`
	DeviceID  string     `json:"device_id"`
	Latitude  float64    `json:"latitude"`
	Longitude float64    `json:"longitude"`
	Altitude  OptFloat64 `json:"altitude"`
	Speed     OptFloat64 `json:"speed"`
	Accuracy  OptFloat64 `json:"accuracy"`
	PlaceName OptString  `json:"place_name"`
	Timestamp string     `json:"timestamp"`
}

// GetUserID returns the value of UserID.
func (s *UserLocation) GetUserID() string {
	return s.UserID
}

// GetDeviceID returns the value of DeviceID.
func (s *UserLocation) GetDeviceID() string {
	return s.DeviceID
}

// GetLatitude returns the value of Latitude.
func (s *UserLocation) GetLatitude() float64 {
	return s.Latitude
}

// GetLongitude returns the value of Longitude.
func (s *UserLocation) GetLongitude() float64 {
	return s.Longitude
}

// GetAltitude returns the value of Altitude.
func (s *UserLocation) GetAltitude() OptFloat64 {
	return s.Altitude
}

// GetSpeed returns the value of Speed.
func (s *UserLocation) GetSpeed() OptFloat64 {
	return s.Speed
}

// GetAccuracy returns the value of Accuracy.
func (s *UserLocation) GetAccuracy() OptFloat64 {
	return s.Accuracy
}

// GetPlaceName returns the value of PlaceName.
func (s *UserLocation) GetPlaceName() OptString {
	return s.PlaceName
}

// GetTimestamp returns the value of Timestamp.
func (s *UserLocation) GetTimestamp() string {
	return s.Timestamp
}

// SetUserID sets the value of UserID.
func (s *UserLocation) SetUserID(val string) {
	s.UserID = val
}

// SetDeviceID sets the value of DeviceID.
func (s *UserLocation) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetLatitude sets the value of Latitude.
func (s *UserLocation) SetLatitude(val float64) {
	s.Latitude = val
}

// SetLongitude sets the value of Longitude.
func (s *UserLocation) SetLongitude(val float64) {
	s.Longitude = val
}

// SetAltitude sets the value of Altitude.
func (s *UserLocation) SetAltitude(val OptFloat64) {
	s.Altitude = val
}

// SetSpeed sets the value of Speed.
func (s *UserLocation) SetSpeed(val OptFloat64) {
	s.Speed = val
}

// SetAccuracy sets the value of Accuracy.
func (s *UserLocation) SetAccuracy(val OptFloat64) {
	s.Accuracy = val
}

// SetPlaceName sets the value of PlaceName.
func (s *UserLocation) SetPlaceName(val OptString) {
	s.PlaceName = val
}

// SetTimestamp sets the value of Timestamp.
func (s *UserLocation) SetTimestamp(val string) {
	s.Timestamp = val
}

// Ref: #/components/schemas/UserMemory
type UserMemory struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *UserMemory) GetID() string {
	return s.ID
}

// GetContent returns the value of Content.
func (s *UserMemory) GetContent() string {
	return s.Content
}

// GetCreatedAt returns the value of CreatedAt.
func (s *UserMemory) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *UserMemory) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *UserMemory) SetID(val string) {
	s.ID = val
}

// SetContent sets the value of Content.
func (s *UserMemory) SetContent(val string) {
	s.Content = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *UserMemory) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *UserMemory) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

type UserMetadata map[string]jx.Raw

func (s *UserMetadata) init() UserMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type UserRole string

const (
	UserRoleOwner  UserRole = "owner"
	UserRoleMember UserRole = "member"
	UserRoleGuest  UserRole = "guest"
)

// AllValues returns all UserRole values.
func (UserRole) AllValues() []UserRole {
	return []UserRole{
		UserRoleOwner,
		UserRoleMember,
		UserRoleGuest,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserRole) MarshalText() ([]byte, error) {
	switch s {
	case UserRoleOwner:
		return []byte(s), nil
	case UserRoleMember:
		return []byte(s), nil
	case UserRoleGuest:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserRole) UnmarshalText(data []byte) error {
	switch UserRole(data) {
	case UserRoleOwner:
		*s = UserRoleOwner
		return nil
	case UserRoleMember:
		*s = UserRoleMember
		return nil
	case UserRoleGuest:
		*s = UserRoleGuest
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UsersGetOK struct {
	Data User `json:"data"`
}

// GetData returns the value of Data.
func (s *UsersGetOK) GetData() User {
	return s.Data
}

// SetData sets the value of Data.
func (s *UsersGetOK) SetData(val User) {
	s.Data = val
}

type UsersGuildsOK struct {
	Data []UserGuild `json:"data"`
}

// GetData returns the value of Data.
func (s *UsersGuildsOK) GetData() []UserGuild {
	return s.Data
}

// SetData sets the value of Data.
func (s *UsersGuildsOK) SetData(val []UserGuild) {
	s.Data = val
}

// Paginated list wrapper.
type UsersListOK struct {
	Data  []User `json:"data"`
	Total int32  `json:"total"`
}

// GetData returns the value of Data.
func (s *UsersListOK) GetData() []User {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *UsersListOK) GetTotal() int32 {
	return s.Total
}

// SetData sets the value of Data.
func (s *UsersListOK) SetData(val []User) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *UsersListOK) SetTotal(val int32) {
	s.Total = val
}

type UsersMemoriesOK struct {
	Data []UserMemory `json:"data"`
}

// GetData returns the value of Data.
func (s *UsersMemoriesOK) GetData() []UserMemory {
	return s.Data
}

// SetData sets the value of Data.
func (s *UsersMemoriesOK) SetData(val []UserMemory) {
	s.Data = val
}

// Ref: #/components/schemas/VecStats
type VecStats struct {
	TotalMemories int32   `json:"total_memories"`
	EmbeddedCount int32   `json:"embedded_count"`
	MissingCount  int32   `json:"missing_count"`
	CoveragePct   float64 `json:"coverage_pct"`
}

// GetTotalMemories returns the value of TotalMemories.
func (s *VecStats) GetTotalMemories() int32 {
	return s.TotalMemories
}

// GetEmbeddedCount returns the value of EmbeddedCount.
func (s *VecStats) GetEmbeddedCount() int32 {
	return s.EmbeddedCount
}

// GetMissingCount returns the value of MissingCount.
func (s *VecStats) GetMissingCount() int32 {
	return s.MissingCount
}

// GetCoveragePct returns the value of CoveragePct.
func (s *VecStats) GetCoveragePct() float64 {
	return s.CoveragePct
}

// SetTotalMemories sets the value of TotalMemories.
func (s *VecStats) SetTotalMemories(val int32) {
	s.TotalMemories = val
}

// SetEmbeddedCount sets the value of EmbeddedCount.
func (s *VecStats) SetEmbeddedCount(val int32) {
	s.EmbeddedCount = val
}

// SetMissingCount sets the value of MissingCount.
func (s *VecStats) SetMissingCount(val int32) {
	s.MissingCount = val
}

// SetCoveragePct sets the value of CoveragePct.
func (s *VecStats) SetCoveragePct(val float64) {
	s.CoveragePct = val
}
